#!/usr/bin/with-contenv bash

[ -f /usr/sbin/cron ] || ( echo "**** installing cron ****" & apt-get update & apt-get install cron -y)

[ -f /config/crontab ] && ( echo "**** copying crontab from /config/crontab ****" & cp /config/crontab /etc/crontabs ) || ( echo "**** error: crontab not found in expected source loaction /config/crontab ****" )

/usr/sbin/cron -f -S -l 0 -c /etc/crontabs