#!/usr/bin/with-contenv bash

[ -f /usr/sbin/cron ] || ( echo "**** installing cron ****" & apt-get update & apt-get install cron -y)

[ -f /config/crontab ] && ( echo "**** setting up crontab using /config/crontab ****" & cp /config/crontab /etc/crontabs & cat /etc/crontabs) || ( echo "**** warning: no crontab not found at expected source location /config/crontab ****" )

/usr/sbin/cron -f -l 0 /etc/crontabs