#!/bin/bash

BACKUP_FILE=$(find /config/Library/Application\ Support/Plex\ Media\ Server/Plug-in\ Support/Databases/ -name com.plexapp.plugins.library.db-20[0-9][0-9]-[0-9][0-9]-[0-9][0-9] | sort | tail -n 1)
LIBRARY_FILE=/config/Library/Application\ Support/Plex\ Media\ Server/Plug-in\ Support/Databases/com.plexapp.plugins.library.db
BACKUP_DATE=$(basename "$BACKUP_FILE")
BACKUP_DATE=${BACKUP_DATE#*-}

LIBRARY_BLOB_FILE=/config/Library/Application\ Support/Plex\ Media\ Server/Plug-in\ Support/Databases/com.plexapp.plugins.library.blobs.db
BACKUP_BLOB_FILE=${LIBRARY_BLOB_FILE}-${BACKUP_DATE}
BACKUP_BLOB_FILE=$(find /config/Library/Application\ Support/Plex\ Media\ Server/Plug-in\ Support/Databases/ -name com.plexapp.plugins.library.blobs.db-20[0-9][0-9]-[0-9][0-9]-[0-9][0-9] | sort | tail -n 1)

# check latest 2 server logs for db corruption warnings
[[ -f /config/Library/Application\ Support/Plex\ Media\ Server/Logs/Plex\ Media\ Server.log ]] && \
    [[ $(cat /config/Library/Application\ Support/Plex\ Media\ Server/Logs/Plex\ Media\ Server.log | grep "database disk image is malformed") ]] && \
    [[ -f /config/Library/Application\ Support/Plex\ Media\ Server/Logs/Plex\ Media\ Server.1.log ]] && \
    [[ $(cat /config/Library/Application\ Support/Plex\ Media\ Server/Logs/Plex\ Media\ Server.1.log | grep "database disk image is malformed") ]] && \
    LIBRARY_DB_CORRUPT="TRUE" || LIBRARY_DB_CORRUPT=

if [[ -f "$BACKUP_BLOB_FILE" ]] && \
    ( [[ $LIBRARY_DB_CORRUPT = "TRUE" ]] && echo "Library DB corrupt, restoring from latest backup."); then

    echo "Loaded plex library db from backup: $BACKUP_FILE"
    cp "$BACKUP_FILE" "$LIBRARY_FILE"
    rm "${LIBRARY_FILE}-shm"
    rm "${LIBRARY_FILE}-wal"

    echo "Loaded plex library blobs from backup: $BACKUP_BLOB_FILE"
    cp "$BACKUP_BLOB_FILE" "$LIBRARY_BLOB_FILE"
    rm "${LIBRARY_BLOB_FILE}-shm"
    rm "${LIBRARY_BLOB_FILE}-wal"
else
    echo "error: com.plexapp.plugins.library.blobs.db backup with date matching com.plexapp.plugins.library.db backup not found. backup restore aborted"
fi

