version: '3.3'
networks:
    internal:
services:
    rclone_media_scanner1:
        restart: always
        labels:
            - "autoheal=true"
        environment:
            - TZ=Australia/Melbourne
            - PGID=${GROUPID}
            - PUID=${USERID}   
            - 'HEALTHCHECK_MOUNTS=/data'
            - 'HEALTHCHECK_PATHS=/data'
            # - RCLONE_LOG_FILE=/config/rclone_media_scanner_mount_1.log
            - RCLONE_LOG_LEVEL=INFO
            - 'RCLONE_REMOTE_PATH=secure_media_scanner:'
            - 'RCLONE_MOUNT_USER_OPTS=--read-only --use-json-log --acd-templink-threshold 1g --buffer-size 8M --timeout 5s --contimeout 5s --stats 300s --dir-cache-time 30m --multi-thread-streams=20 --allow-non-empty --allow-other --rc-web-gui --rc-web-gui-update --rc-web-gui-no-open-browser --rc-user ${RCLONE_USER} --rc-pass ${RCLONE_PASSWORD}'
            - RCLONE_CONFIG_GDRIVE_MOLE_TEAM_DRIVE=${RCLONE_CONFIG_GDRIVE_TEAM_DRIVE_1}
            - RCLONE_CONFIG_GDRIVE_WOLF_TEAM_DRIVE=${RCLONE_CONFIG_GDRIVE_TEAM_DRIVE_1}
        volumes:
            - '${DOCKER_ROOT}/rclone/:/config:rw'
            - '${DOCKER_ROOT}/scripts/:/scripts:ro'
            - '${DOCKER_ROOT}/mnt/rclone/scanner_secure_media:/data:rshared'
        networks:
            - internal
        ports:
            - "25571:5574"
        logging:
            options:
                max-size: 20m
        devices:
            - /dev/fuse
        cap_add:
            - SYS_ADMIN
        security_opt:
            - apparmor:unconfined
        image: wiserain/rclone
        healthcheck:
            test: ["CMD-SHELL", "sh /scripts/healthcheck"]
            interval: 120s
            timeout: 10s
            retries: 1
            start_period: 5s
    rclone_media_scanner2:
        restart: always
        labels:
            - "autoheal=true"
        environment:
            - TZ=Australia/Melbourne
            - PGID=${GROUPID}
            - PUID=${USERID}   
            - 'HEALTHCHECK_MOUNTS=/data'
            - 'HEALTHCHECK_PATHS=/data'
            # - RCLONE_LOG_FILE=/config/rclone_media_scanner_mount_2.log
            - RCLONE_LOG_LEVEL=INFO
            - 'RCLONE_REMOTE_PATH=secure_media_scanner:'
            - 'RCLONE_MOUNT_USER_OPTS=--read-only --use-json-log --acd-templink-threshold 1g --buffer-size 8M --timeout 5s --contimeout 5s --stats 300s --dir-cache-time 30m --multi-thread-streams=20 --allow-non-empty --allow-other --rc-web-gui --rc-web-gui-update --rc-web-gui-no-open-browser --rc-user ${RCLONE_USER} --rc-pass ${RCLONE_PASSWORD}'
            - RCLONE_CONFIG_GDRIVE_MOLE_TEAM_DRIVE=${RCLONE_CONFIG_GDRIVE_TEAM_DRIVE_2}
            - RCLONE_CONFIG_GDRIVE_WOLF_TEAM_DRIVE=${RCLONE_CONFIG_GDRIVE_TEAM_DRIVE_2}
        volumes:
            - '${DOCKER_ROOT}/rclone/:/config:rw'
            - '${DOCKER_ROOT}/scripts/:/scripts:ro'
            - '${DOCKER_ROOT}/mnt/rclone/scanner_secure_media2:/data:rshared'
        networks:
            - internal
        ports:
            - "25572:5574"
        logging:
            options:
                max-size: 20m
        devices:
            - /dev/fuse
        cap_add:
            - SYS_ADMIN
        security_opt:
            - apparmor:unconfined
        image: wiserain/rclone
        healthcheck:
            test: ["CMD-SHELL", "sh /scripts/healthcheck"]
            interval: 120s
            timeout: 10s
            retries: 1
            start_period: 5s
    rclone_media_scanner3:
        restart: always
        labels:
            - "autoheal=true"
        environment:
            - TZ=Australia/Melbourne
            - PGID=${GROUPID}
            - PUID=${USERID}   
            - 'HEALTHCHECK_MOUNTS=/data'
            - 'HEALTHCHECK_PATHS=/data'
            # - RCLONE_LOG_FILE=/config/rclone_media_scanner_mount_3.log
            - RCLONE_LOG_LEVEL=INFO
            - 'RCLONE_REMOTE_PATH=secure_media_scanner:'
            - 'RCLONE_MOUNT_USER_OPTS=--read-only --use-json-log --acd-templink-threshold 1g --buffer-size 8M --timeout 5s --contimeout 5s --stats 300s --dir-cache-time 30m --multi-thread-streams=20 --allow-non-empty --allow-other --rc-web-gui --rc-web-gui-update --rc-web-gui-no-open-browser --rc-user ${RCLONE_USER} --rc-pass ${RCLONE_PASSWORD}'
            - RCLONE_CONFIG_GDRIVE_MOLE_TEAM_DRIVE=${RCLONE_CONFIG_GDRIVE_TEAM_DRIVE_3}
            - RCLONE_CONFIG_GDRIVE_WOLF_TEAM_DRIVE=${RCLONE_CONFIG_GDRIVE_TEAM_DRIVE_3}
        volumes:
            - '${DOCKER_ROOT}/rclone/:/config:rw'
            - '${DOCKER_ROOT}/scripts/:/scripts:ro'
            - '${DOCKER_ROOT}/mnt/rclone/scanner_secure_media3:/data:rshared'
        networks:
            - internal
        ports:
            - "25573:5574"
        logging:
            options:
                max-size: 20m
        devices:
            - /dev/fuse
        cap_add:
            - SYS_ADMIN
        security_opt:
            - apparmor:unconfined
        image: wiserain/rclone
        healthcheck:
            test: ["CMD-SHELL", "sh /scripts/healthcheck"]
            interval: 120s
            timeout: 10s
            retries: 1
            start_period: 5s
    scanner_mergerfs:
        command: # -f # foreground operation
            - -o
            - allow_other # allow access to other users
            - -o
            - auto_cache # enable caching based on modification times
            - -o
            - auto_unmount # auto unmount on process termination
            - -o
            - direct_io # use direct I/O
            - -o
            - gid=${GROUPID} # set file group
            - -o
            - sync_read # perform reads synchronously
            - -o
            - uid=${USERID} # set file owner
            - /mnt/rclone/scanner_secure_media=RO:/mnt/rclone/scanner_secure_media2=RO:/mnt/rclone/scanner_secure_media3=RO # source paths
            - /data/media # mergerfs mounts
        restart: always
        labels:
            - "autoheal=true"
        environment:
            - TZ=Australia/Melbourne
            - PUID=${USERID}
            - PGID=${GROUPID}
            - 'HEALTHCHECK_MOUNTS=/data/media'
            - 'HEALTHCHECK_PATHS=/data/media/mountcheck /data/media/Media/movies /data/media/Media/movies-4k /data/media/Media/tv /data/media/Media/tv-4k'
        volumes:
            - '${DOCKER_ROOT}/mnt/mergerfs/scanner:/data:rshared'
            - '${DOCKER_ROOT}/mnt/rclone:/mnt/rclone:rshared'
            - '${DOCKER_ROOT}/scripts/:/scripts:ro'
        networks:
            - internal
        logging:
            options:
                max-size: 20m
        devices:
            - /dev/fuse
        cap_add:
            - SYS_ADMIN
        security_opt:
            - apparmor:unconfined
        image: hotio/mergerfs
        healthcheck:
            test: ["CMD-SHELL", "sh /scripts/healthcheck"]
            interval: 30s
            timeout: 25s
            retries: 3
            start_period: 10s
    plex_scanner:
        # container_name: pdp-plex-scanner
        networks:
            - internal
        restart: unless-stopped
        labels:
            - "autoheal=true"
        environment:
            - TZ=Australia/Melbourne
            - PLEX_CLAIM=${PLEX_CLAIM}
            - PLEX_UID=${USERID}   
            - PLEX_GID=${GROUPID}
            - VERSION=latest
            - 'NVIDIA_VISIBLE_DEVICES='
            - PUID=${USERID}   
            - PGID=${GROUPID}
            - 'HEALTHCHECK_MOUNTS=/plex/media'
            - 'HEALTHCHECK_PATHS=/plex/media/Media/movies /plex/media/Media/movies-4k /plex/media/Media/tv /plex/media/Media/tv-4k'
        volumes:
            - '${DOCKER_ROOT}/mnt/mergerfs/scanner:/plex:rslave' # should contain subfolder: media
            - '${DOCKER_ROOT}/plex-scanner/:/config:rw'
            - '${DOCKER_ROOT}/scripts/:/scripts:ro'
        ports:
            - "34400:32400"
        image: linuxserver/plex
        healthcheck:
            test: ["CMD-SHELL", "bash /scripts/plexhealthcheck"]
            interval: 300s
            timeout: 60s
            retries: 3
            start_period: 30s
        depends_on:
            scanner_mergerfs:
                condition: service_healthy
    plex-meta-manager:
        image: lscr.io/linuxserver/plex-meta-manager:latest
        container_name: plex-meta-manager
        environment:
            - TZ=Australia/Melbourne
            - PLEX_UID=${USERID}   
            - PLEX_GID=${GROUPID}
            - PMM_CONFIG=/config/config.yml #optional
            - PMM_TIME=03:00 #optional
            - PMM_RUN=True #optional
            - PMM_TEST=False #optional
            - PMM_NO_MISSING=False #optional
            - PMM_DELETE_COLLECTIONS=False #optional
            - UMASK=022
        volumes:
            - '${DOCKER_ROOT}/plex-meta-manager:/config'
        restart: unless-stopped