version: '3.3'
services:
    rclone_only:
        labels:
            - "autoheal=true"
        image: slink42/rclone
        restart: always
        networks:
            - bridge
            - internal
        ports:
            - "25574:5574"
        env_file: 
            - "${DOCKER_ROOT}/config/rclone.env"
        volumes:
            - '${DOCKER_ROOT}/rclone/config:/config/rclone'
            - '${DOCKER_ROOT}/mnt:/mnt:shared'
        devices:
            - /dev/fuse
        cap_add:
            - SYS_ADMIN
        security_opt:
            - apparmor:unconfined
        logging:
            options:
                max-size: 20m
        environment:
            - PUID=${GROUPID}
            - PGID=${USERID}
            - TZ=Australia/Melbourne
            - RCLONE_LOG_LEVEL=INFO
            - 'RCLONE_REMOTE_PATH=secure_media_crypt:'
            - 'RCLONE_MOUNT_BASIC_OPTS= --uid=${PUID:-911} --gid=${PGID:-911} --cache-dir=/cache --use-mmap --allow-other --umask=002 --rc --rc-no-auth --rc-addr=:5574 '
            - 'RCLONE_MOUNT_USER_OPTS= -v --read-only --use-json-log --acd-templink-threshold 1g --buffer-size 8M --timeout 5s --contimeout 5s --stats 300s --dir-cache-time 30m --multi-thread-streams=20 --allow-non-empty --allow-other --rc-web-gui --rc-web-gui-no-open-browser --rc-user ${RCLONE_USER} --rc-pass ${RCLONE_PASSWORD} '
            - 'MERGED_DEST=/mnt/rclone_only'
            - 'PLEXDRIVE_CONFIG_FOLDER=/deliberately_wrong_path' # makes sure plexdrive doesn't run due to config files found in path
    plex_scanner:
        networks:
            - bridge
            - internal
        restart: always
        labels:
            - "autoheal=true"
        environment:
            - TZ=Australia/Melbourne
            - PLEX_CLAIM=${PLEX_CLAIM}
            - PLEX_UID=${USERID}   
            - PLEX_GID=${GROUPID}
            - VERSION=latest
            - 'NVIDIA_VISIBLE_DEVICES='
            - PUID=${USERID}   
            - PGID=${GROUPID}
            - 'HEALTHCHECK_MOUNTS=/plex/media'
            - 'HEALTHCHECK_PATHS=/plex/media/mountcheck'
            - 'LIB_META_BACKUP_PATH_MASTER=/backups/meta'
            - 'LIB_META_BACKUP_CRON=35 00 * * *'
            - 'LIB_DB_BACKUP_CRON=35 00 * * *'
        volumes:
            - '${DOCKER_ROOT}/mnt/rclone_only:/plex:rslave' # should contain subfolder: media
            - '${DOCKER_ROOT}/plex-scanner/:/config:rw'
            - '${LARGE_DISK_ROOT}/plex_library_backup/meta:/backups/meta:rw'
            - '${LARGE_DISK_ROOT}/tmp:/tmp:rw'
        ports:
            - "34400:32400"
        logging:
            options:
                max-size: 20m
        image: slink42/plex
        healthcheck:
            test: ["CMD-SHELL", "bash /scripts/plexhealthcheck"]
            interval: 300s
            timeout: 60s
            retries: 3
            start_period: 30s
        # depends_on:
        #     rclone_only:
        #         condition: service_healthy
    plex-meta-manager:
        image: lscr.io/linuxserver/plex-meta-manager:latest
        environment:
            - TZ=Australia/Melbourne
            - PLEX_UID=${USERID}   
            - PLEX_GID=${GROUPID}
            - PMM_CONFIG=/config/config.yml #optional
            - PMM_TIME=03:00 #optional
            - PMM_RUN=True #optional
            - PMM_TEST=False #optional
            - PMM_NO_MISSING=False #optional
            - PMM_DELETE_COLLECTIONS=False #optional
            - UMASK=022
        volumes:
            - '${DOCKER_ROOT}/plex-meta-manager:/config'
        logging:
            options:
                max-size: 20m
        restart: always
        networks:
            - bridge
            - internal