version: '3.3'
networks:
    internal:
        internal: true
    bridge:
        driver: bridge
    hostnet:
        external: true
        name: host
services:
    rclone_pd:
        labels:
            - "autoheal=true"
        image: slink42/rclone
        restart: always
        networks:
            - bridge
            - internal
        ports:
            - "15574:5574"
        env_file: 
            - "${DOCKER_ROOT}/config/rclone.env"
        volumes:
            - '${DOCKER_ROOT}/rclone/config:/config/rclone'
            - '${DOCKER_ROOT}/plexdrive/log:/log'
            - '${DOCKER_ROOT}/plexdrive/cache:/cache'
            - '${DOCKER_ROOT}/plexdrive/config:/config/plexdrive'
            - '${DOCKER_ROOT}/mnt:/mnt:shared'
        devices:
            - /dev/fuse
        cap_add:
            - SYS_ADMIN
        security_opt:
            - apparmor:unconfined
        logging:
            options:
                max-size: 20m
        environment:
            - PUID=${GROUPID}
            - PGID=${USERID}
            - TZ=Australia/Melbourne
            - 'RCLONE_REMOTE_PATH=plexdrive_secure_media_4k_crypt:'
            - 'RCLONE_MOUNT_BASIC_OPTS= --uid=${PUID:-911} --gid=${PGID:-911} --cache-dir=/cache --use-mmap --allow-other --umask=002 --rc --rc-no-auth --rc-addr=:5574 '
            - 'RCLONE_MOUNT_USER_OPTS= -v --read-only --use-json-log --acd-templink-threshold 1g --buffer-size 8M --timeout 5s --contimeout 5s --stats 300s --dir-cache-time 30m --multi-thread-streams=20 --allow-non-empty --allow-other --rc-web-gui --rc-web-gui-no-open-browser --rc-user rclone --rc-pass rclone '
            - 'MERGED_DEST=/mnt/rclone_pd'
            - 'PLEXDRIVE_REMOTE=secure_media'
            - 'PLEXDRIVE_MOUNT_BASIC_OPTS= --config /config/ --uid=${PUID:-911} --gid=${PGID:-911} --umask=0100775 '
            #  - 'PLEXDRIVE_MOUNT_USER_OPTS= -o allow_other,read_only,nonempty,auto_unmount --verbosity=3 --max-chunks=10 --chunk-size=20M --chunk-check-threads=20 --chunk-load-threads=4 --chunk-load-ahead=5 '
            #  - 'PLEXDRIVE_MOUNT_USER_OPTS= -o read_only -v 2 --max-chunks=20 --chunk-size=32M --chunk-check-threads=2 --chunk-load-threads=3 --chunk-load-ahead=5'
            - 'PLEXDRIVE_MOUNT_USER_OPTS= -o allow_other,read_only -v 1 --max-chunks=200 --chunk-size=5M --chunk-check-threads=3 --chunk-load-threads=10 --chunk-load-ahead=50'
    plex_streamer:
        network_mode: host
        # networks:
        #     - bridge
        #     - internal
        restart: always
        labels:
            - "autoheal=true"
        environment:
            - TZ=Australia/Melbourne
            - HOST_OS=Unraid
            - PLEX_CLAIM=${PLEX_CLAIM}
            - PLEX_UID=${USERID}
            - PLEX_GID=${GROUPID}
            - VERSION=latest
            - 'NVIDIA_VISIBLE_DEVICES='
            - TCP_PORT_32400=32400
            - TCP_PORT_3005=3005
            - TCP_PORT_8324=8324
            - TCP_PORT_32469=32469
            - UDP_PORT_1900=1900
            - UDP_PORT_32410=32410
            - UDP_PORT_32412=32412
            - UDP_PORT_32413=32413
            - UDP_PORT_32414=32414
            - PUID=${USERID}
            - PGID=${GROUPID}
            - LOAD_LIBRARY_DB_TO_MEMORY=${LOAD_LIBRARY_DB_TO_MEMORY}
            - 'SCANNER_LIBRARY_PATH=/mnt/plex-scanner/Library/Application Support/Plex Media Server'
            - 'HEALTHCHECK_MOUNTS=/plex/media'
            - 'HEALTHCHECK_PATHS=/plex/media/mountcheck'
            - 'LIB_BACKUP_PATH_MASTER=/backups/databases'
            - 'LIB_BACKUP_PATH_LOCAL=/config/Library/Application Support/Plex Media Server/Plug-in Support/Databases'
            - 'LIB_RELOAD_CRON=35 5 * * *'
            - 'LIB_META_BACKUP_PATH_MASTER=/backups/meta'
        volumes:
            - '${DOCKER_ROOT}/plex-streamer/transcode:/transcode:rw'
            - '${DOCKER_ROOT}/mnt/rclone_pd:/plex:slave'
            - '${DOCKER_ROOT}/plex-streamer/:/config:rw'
            - '${LARGE_DISK_ROOT}/plex_master_backup:/backups:rw'
            - '${LARGE_DISK_ROOT}/tmp:/tmp:rw'
        tmpfs:
            - /ram_disk
        ports:
            - "32400:32400"
        logging:
            options:
                max-size: 20m
        image: slink42/plex
        # depends_on:
        #     rclone:
        #         condition: service_healthy
    autoheal:
        image: willfarrell/autoheal
        environment:
            - AUTOHEAL_CONTAINER_LABEL=autoheal
            - AUTOHEAL_INTERVAL=5
            - DOCKER_SOCK=/var/run/docker.sock
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        networks:
            - internal
        logging:
            options:
                max-size: 20m
        restart: always
    watchtower:
        image: containrrr/watchtower
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        command: --interval 30 --include-stopped
        logging:
            options:
                max-size: 20m
        restart: always

volumes:
    empty_volume: