version: '3.3'
networks:
    support:
        driver: bridge
services:
    tailscale:
        hostname: portainer_agent                         # This will become the tailscale device name
        image: tailscale/tailscale
        volumes:
            - ${DOCKER_ROOT}/config:/config"
            - ${DOCKER_ROOT}/tailscale:/var/lib"        # State data will be stored in this directory
            - "/dev/net/tun:/dev/net/tun"           # Required for tailscale to work
        cap_add:                                    # Required for tailscale to work
          - net_admin
          - sys_module
        command: tailscale up --authkey=$(cat /config/install.env | grep TAILSCALE_PLEX_CLIENT_AUTHKEY | sed -e s/^[^=]*=//)
        networks:
            - support
        restart: always
    portainer_agent:
        image: portainer/agent:latest
        network_mode: service:tailscale
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - /var/lib/docker/volumes:/var/lib/docker/volumes
        restart: always
        depends_on:
            - tailscale
    portainer_portal_wg:
        restart: always
        image: portainer/portainer-ce
        command: -H tcp://127.0.0.1:9001 --tlsskipverify
        volumes:
            - portainer_data:/data
        depends_on:
            - tailscale
        network_mode: service:tailscale
    ubuntu:
        depends_on:
            - tailscale
        image: ubuntu
        network_mode: service:tailscale
        command: ["sleep","infinity"]
    portainer_portal:
        restart: always
        image: portainer/portainer-ce
        volumes:
            - portainer_local_data:/data
            - /var/run/docker.sock:/var/run/docker.sock
            - /var/lib/docker/volumes:/var/lib/docker/volumes
        networks:
            - support
        ports:
            - "9010:9000"

volumes:
    portainer_data:
    portainer_local_data:
