version: '3.3'
networks:
    internal:
services:
    plex:
        container_name: pdp-plex
        # network_mode: bridge
        networks:
            - internal
        restart: always
        labels:
            - "autoheal=true"
        environment:
            - TZ=Australia/Melbourne
            - HOST_OS=Unraid
            - PLEX_CLAIM=claim-xxxxxxxxxxxxxxx
            - PLEX_UID=99
            - PLEX_GID=100
            - VERSION=latest
            - 'NVIDIA_VISIBLE_DEVICES='
            - 'RCLONE_MEDIA_PATH=/mnt/rclone/secure_media/Media'
            - 'PLEXDRIVE_MEDIA_PATH=/mnt/rclone/secure_media_plexdrive/Media'
            - 'PLEXDRIVE_MEDIA_FOLDERS=movies-4k tv-4k'
            - 'SCANNER_LIBRARY_PATH=/mnt/plex-scanner/Library/Application Support/Plex Media Server'
            - 'STREAMER_LIBRARY_PATH=/mnt/plex-streamer/Library/Application Support/Plex Media Server'
            - TCP_PORT_32400=32400
            - TCP_PORT_3005=3005
            - TCP_PORT_8324=8324
            - TCP_PORT_32469=32469
            - UDP_PORT_1900=1900
            - UDP_PORT_32410=32410
            - UDP_PORT_32412=32412
            - UDP_PORT_32413=32413
            - UDP_PORT_32414=32414
            - PUID=99
            - PGID=100
            - 'HEALTHCHECK_MOUNTS=/mnt/rclone/secure_media /mnt/rclone/secure_media_plexdrive'
            - 'HEALTHCHECK_PATHS=/plex/media/Media/movies /plex/media/Media/movies-4k'
        volumes:
            - '${DOCKER_ROOT}/plex-streamer/transcode:/transcode:rw'
            - '${DOCKER_ROOT}/mnt/rclone:/mnt/rclone:rshared'
            - '${DOCKER_ROOT}/plex-scanner/:/mnt/plex-scanner:rw'
            - '${DOCKER_ROOT}/plex-streamer/:/config:rw'
            - '${DOCKER_ROOT}/scripts/:/scripts:ro'
        ports:
            - "32400:32400"
        image: linuxserver/plex
        healthcheck:
            test: ["CMD-SHELL", "bash /scripts/plexhealthcheck"]
            interval: 300s
            timeout: 60s
            retries: 3
            start_period: 30s
        # depends_on:
            # rclone_media:
                # condition: service_healthy
    rclone_plexdrive:
        # container_name: pdp-rclone-plexdrive
        command: 'mount --allow-other --allow-non-empty plexdrive_crypt: /mnt/plexdrive_decrypted --log-level INFO'
        restart: always
        labels:
            - "autoheal=true"
        environment:
            - TZ=Australia/Melbourne
            - PGID=100
            - PUID=99
            - 'HEALTHCHECK_MOUNTS=/mnt/plexdrive /mnt/plexdrive_decrypted'
            - 'HEALTHCHECK_PATHS=/mnt/plexdrive'
        volumes:
            - '${DOCKER_ROOT}/mnt/plexdrive/secure_media/:/mnt/plexdrive:rshared'
            - '${DOCKER_ROOT}/mnt/rclone/secure_media_plexdrive:/mnt/plexdrive_decrypted:rshared'
            - '${DOCKER_ROOT}/rclone/:/config/rclone:rshared'
            - '${DOCKER_ROOT}/scripts/:/scripts:ro'
        networks:
            - internal
        logging:
            options:
                max-size: 20m
        devices:
            - /dev/fuse
        cap_add:
            - SYS_ADMIN
        security_opt:
            - apparmor:unconfined
        image: rclone/rclone
        healthcheck:
            test: ["CMD-SHELL", "sh /scripts/healthcheck"]
            interval: 300s
            timeout: 60s
            retries: 3
            start_period: 30s
    rclone_media:
        # container_name: pdp-rclone-secure-media
        command: 'mount --read-only --acd-templink-threshold 1g --buffer-size 8M --timeout 5s --contimeout 5s --log-level INFO --stats 300s --dir-cache-time 30m --multi-thread-streams=20  secure_media: /mnt/secure_media --allow-non-empty --allow-other'
        restart: always
        labels:
            - "autoheal=true"
        environment:
            - TZ=Australia/Melbourne
            - PGID=100
            - PUID=99
            - 'HEALTHCHECK_MOUNTS=/mnt/secure_media'
            - 'HEALTHCHECK_PATHS=/mnt/secure_media'
        volumes:
            - '${DOCKER_ROOT}/mnt/rclone/secure_media:/mnt/secure_media:rshared'
            - '${DOCKER_ROOT}/rclone/:/config/rclone'
            - '${DOCKER_ROOT}/scripts/:/scripts:ro'
        networks:
            - internal
        logging:
            options:
                max-size: 20m
        devices:
            - /dev/fuse
        cap_add:
            - SYS_ADMIN
        security_opt:
            - apparmor:unconfined
        image: rclone/rclone
        healthcheck:
            test: ["CMD-SHELL", "sh /scripts/healthcheck"]
            interval: 300s
            timeout: 60s
            retries: 3
            start_period: 30s
    plexdrive:
        # container_name: pdp-plexdrive-secure_media
        restart: always
        labels:
            - "autoheal=true"
        environment:
            - TZ=Australia/Melbourne
            - PUID=0
            - PGID=0
            - POOLING_FS=unionfs
            - 'PLEXDRIVE_OPTS=-v 2 --max-chunks=10 --chunk-size=20M --chunk-check-threads=20 --chunk-load-threads=4 --chunk-load-ahead=5 --drive-id=0ALNBa0QBHhldUk9PVA -o allow_other,read_only,nonempty'
        volumes:
            - '${DOCKER_ROOT}/plexdrive/config:/config:rw'
            - '${DOCKER_ROOT}/plexdrive/cache:/cache:rw'
            - '${DOCKER_ROOT}/mnt/plexdrive/secure_media:/data:rshared'
            - '${DOCKER_ROOT}/test-path/:/local/:ro'
        networks:
            - internal
        logging:
            options:
                max-size: 20m
        devices:
            - /dev/fuse
        cap_add:
            - SYS_ADMIN
        security_opt:
            - apparmor:unconfined
        image: 'wiserain/plexdrive:5.1.0'
    rclone_library_sync:
        # container_name: pdp-rclone-library-download
        # # command: 'lsd SECURE_BACKUP:'
        # library download from master
        command: 'copy SECURE_BACKUP: /config --progress'
        # # library upload from master
        # command: 'sync /config SECURE_BACKUP: --progress'
        labels:
            - "autoheal-library=true"
        #command: 'lsd SECURE_BACKUP:'
        environment:
            - TZ=Australia/Melbourne
            - PGID=100
            - PUID=99
            - RCLONE_CONFIG_CONFIG_BACKUP_TYPE=${RCLONE_CONFIG_CONFIG_BACKUP_TYPE}
            - RCLONE_CONFIG_CONFIG_BACKUP_CLIENT_ID=${RCLONE_CONFIG_CONFIG_BACKUP_CLIENT_ID}
            - RCLONE_CONFIG_CONFIG_BACKUP_CLIENT_SECRET=${RCLONE_CONFIG_CONFIG_BACKUP_CLIENT_SECRET}
            - RCLONE_CONFIG_CONFIG_BACKUP_SCOPE=${RCLONE_CONFIG_CONFIG_BACKUP_SCOPE}
            - 'RCLONE_CONFIG_CONFIG_BACKUP_TOKEN=${RCLONE_CONFIG_CONFIG_BACKUP_TOKEN}'
            - RCLONE_CONFIG_CONFIG_BACKUP_TEAM_DRIVE=${RCLONE_CONFIG_CONFIG_BACKUP_TEAM_DRIVE}
            - RCLONE_CONFIG_SECURE_BACKUP_TYPE=${RCLONE_CONFIG_SECURE_BACKUP_TYPE}
            - 'RCLONE_CONFIG_SECURE_BACKUP_REMOTE=${RCLONE_CONFIG_SECURE_BACKUP_REMOTE}'
            - RCLONE_CONFIG_SECURE_BACKUP_FILENAME_ENCRYPTION=${RCLONE_CONFIG_SECURE_BACKUP_FILENAME_ENCRYPTION}
            - RCLONE_CONFIG_SECURE_BACKUP_DIRECTORY_NAME_ENCRYPTION=${RCLONE_CONFIG_SECURE_BACKUP_DIRECTORY_NAME_ENCRYPTION}
            - RCLONE_CONFIG_SECURE_BACKUP_PASSWORD=${RCLONE_CONFIG_SECURE_BACKUP_PASSWORD}
            - RCLONE_CONFIG_SECURE_BACKUP_PASSWORD2=${RCLONE_CONFIG_SECURE_BACKUP_PASSWORD2}
        volumes:
            - '${DOCKER_ROOT}/plex-streamer/Library/Application Support/Plex Media Server/Plug-in Support/:/config/Library/Application Support/Plex Media Server/Plug-in Support/:rw'
            - '${DOCKER_ROOT}/plex-streamer/custom-cont-init.d/:/config/custom-cont-init.d/:rw'
            - '${DOCKER_ROOT}/plex-streamer/custom-services.d/:/config/custom-services.d/:rw'
            - '${DOCKER_ROOT}/scripts/:/config/scripts:rw'
            - '${DOCKER_ROOT}/setup/:/config/setup:rw'
        networks:
            - internal
        logging:
            options:
                max-size: 20m
        image: rclone/rclone
    autoheal:
        # container_name: pdp-autoheal
        restart: always
        image: willfarrell/autoheal
        environment:
            - AUTOHEAL_CONTAINER_LABEL=autoheal
            - AUTOHEAL_INTERVAL=5
            - DOCKER_SOCK=/var/run/docker.sock
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        networks:
            - internal
    autoheal-library:
        # container_name: pdp-autoheal-library-download
        restart: always
        image: willfarrell/autoheal
        environment:
            - AUTOHEAL_CONTAINER_LABEL=autoheal-library
            - AUTOHEAL_INTERVAL=1440
            - DOCKER_SOCK=/var/run/docker.sock
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        networks:
            - internal
    # rclone_media_scanner:
    #     # container_name: pdp-rclone-secure_media_scanner
    #     command: 'mount --read-only --log-level INFO --stats 300s --dir-cache-time 30m --poll-interval 10m --multi-thread-streams=20  secure_media_scanner: /mnt/secure_media --allow-non-empty --allow-other'
    #     restart: always
    #     labels:
    #         - "autoheal=true"
    #     environment:
    #         - TZ=Australia/Melbourne
    #         - PGID=100
    #         - PUID=99
    #         - 'HEALTHCHECK_MOUNTS=/mnt/secure_media'
    #         - 'HEALTHCHECK_PATHS=/mnt/secure_media'
    #     volumes:
    #         - '${DOCKER_ROOT}/mnt/rclone/secure_media_scanner/:/mnt/secure_media:rshared'
    #         - '${DOCKER_ROOT}/rclone/:/config/rclone:rshared'
    #         - '${DOCKER_ROOT}/scripts/:/scripts:ro'
    #     networks:
    #         - internal
    #     logging:
    #         options:
    #             max-size: 20m
    #     devices:
    #         - /dev/fuse
    #     cap_add:
    #         - SYS_ADMIN
    #     security_opt:
    #         - apparmor:unconfined     
    #     image: rclone/rclone
    #     healthcheck:
    #         test: ["CMD-SHELL", "sh /scripts/healthcheck"]
    #         interval: 300s
    #         timeout: 60s
    #         retries: 3
    #         start_period: 30s
    # plex-scanner:
    #     # container_name: pdp-plex-scanner
    #     networks:
    #         - internal
    #     restart: always
    #     labels:
    #         - "autoheal=true"
    #     environment:
    #         - TZ=Australia/Melbourne
    #         - PLEX_CLAIM=claim-xxxxxxxxxxxxxxx
    #         - PLEX_UID=99
    #         - PLEX_GID=100
    #         - VERSION=latest
    #         - 'NVIDIA_VISIBLE_DEVICES='
    #         - 'PLEXDRIVE_MEDIA_FOLDERS=movies-4k tv-4k'
    #         - PUID=99
    #         - PGID=100
    #         - 'HEALTHCHECK_MOUNTS=/mnt/rclone/secure_media /mnt/rclone/secure_media_plexdrive'
    #         - 'HEALTHCHECK_PATHS=/plex/media/Media/movies /plex/media/Media/movies-4k'
    #     volumes:
    #         - '${DOCKER_ROOT}/mnt/rclone:/mnt/rclone:rshared'
    #         - '${DOCKER_ROOT}/plex-scanner/:/config:rw'
    #         - '${DOCKER_ROOT}/scripts/:/scripts:ro'
    #     ports:
    #         - "34400:32400"
    #     image: linuxserver/plex
    #     healthcheck:
    #         test: ["CMD-SHELL", "bash /scripts/plexhealthcheck"]
    #         interval: 300s
    #         timeout: 60s
    #         retries: 3
    #         start_period: 30s
    #     # depends_on:
    #         # rclone_media_scanner:
    #             # condition: service_healthy