version: '3.3'
networks:
    internal:
        internal: true
    bridge:
        driver: bridge
    hostnet:
        external: true
        name: host
services:
    rclone_media1:
        restart: always
        labels:
            - "autoheal=true"
        environment:
            - TZ=Australia/Melbourne
            - PGID=${GROUPID}
            - PUID=${USERID}
            #- RCLONE_LOG_FILE=/config/rclone_media_mount_1.log
            - RCLONE_LOG_LEVEL=INFO
            - 'RCLONE_REMOTE_PATH=secure_media:'
            - 'RCLONE_MOUNT_USER_OPTS=--read-only --use-json-log --acd-templink-threshold 1g --buffer-size 8M --timeout 5s --contimeout 5s --stats 300s --dir-cache-time 30m --multi-thread-streams=20 --allow-non-empty --allow-other --rc-web-gui --rc-web-gui-no-open-browser --rc-user ${RCLONE_USER} --rc-pass ${RCLONE_PASSWORD}'
            - RCLONE_CONFIG_GDRIVE_MOLE_TEAM_DRIVE=${RCLONE_CONFIG_GDRIVE_TEAM_DRIVE_1}
            - RCLONE_CONFIG_GDRIVE_WOLF_TEAM_DRIVE=${RCLONE_CONFIG_GDRIVE_TEAM_DRIVE_1}
            - MERGED_DEST=/mnt/secure_media
        env_file: 
            - "${DOCKER_ROOT}/config/rclone.env"
        volumes:
            - '${DOCKER_ROOT}/rclone/:/config:rw'
            - '${DOCKER_ROOT}/mnt/rclone:/mnt:shared'
        networks:
            - bridge
            - internal
        ports:
            - "15571:5574"
        logging:
            options:
                max-size: 20m
        devices:
            - /dev/fuse
        cap_add:
            - SYS_ADMIN
        security_opt:
            - apparmor:unconfined
        image: slink42/rclone
    rclone_media2:
        restart: always
        labels:
            - "autoheal=true"
        environment:
            - TZ=Australia/Melbourne
            - PGID=${GROUPID}
            - PUID=${USERID}
            #- RCLONE_LOG_FILE=/config/rclone_media_mount_2.log
            - RCLONE_LOG_LEVEL=INFO
            - 'RCLONE_REMOTE_PATH=secure_media:'
            - 'RCLONE_MOUNT_USER_OPTS=--read-only --use-json-log --acd-templink-threshold 1g --buffer-size 8M --timeout 5s --contimeout 5s --stats 300s --dir-cache-time 30m --multi-thread-streams=20 --allow-non-empty --allow-other --rc-web-gui --rc-web-gui-no-open-browser --rc-user ${RCLONE_USER} --rc-pass ${RCLONE_PASSWORD}'
            - RCLONE_CONFIG_GDRIVE_MOLE_TEAM_DRIVE=${RCLONE_CONFIG_GDRIVE_TEAM_DRIVE_2}
            - RCLONE_CONFIG_GDRIVE_WOLF_TEAM_DRIVE=${RCLONE_CONFIG_GDRIVE_TEAM_DRIVE_2}
            - MERGED_DEST=/mnt/secure_media2
        env_file: 
            - "${DOCKER_ROOT}/config/rclone.env"
        volumes:
            - '${DOCKER_ROOT}/rclone/:/config:rw'
            - '${DOCKER_ROOT}/mnt/rclone:/mnt:shared'
        networks:
            - bridge
            - internal
        ports:
            - "15572:5574"
        logging:
            options:
                max-size: 20m
        devices:
            - /dev/fuse
        cap_add:
            - SYS_ADMIN
        security_opt:
            - apparmor:unconfined
        image: slink42/rclone
    rclone_media3:
        restart: always
        labels:
            - "autoheal=true"
        environment:
            - TZ=Australia/Melbourne
            - PGID=${GROUPID}
            - PUID=${USERID}
            - RCLONE_LOG_FILE=/config/rclone_media_mount_3.log
            - RCLONE_LOG_LEVEL=INFO
            - 'RCLONE_REMOTE_PATH=secure_media:'
            - 'RCLONE_MOUNT_USER_OPTS=--read-only --use-json-log --acd-templink-threshold 1g --buffer-size 8M --timeout 5s --contimeout 5s --stats 300s --dir-cache-time 30m --multi-thread-streams=20 --allow-non-empty --allow-other --rc-web-gui --rc-web-gui-no-open-browser --rc-user ${RCLONE_USER} --rc-pass ${RCLONE_PASSWORD}'
            - RCLONE_CONFIG_GDRIVE_MOLE_TEAM_DRIVE=${RCLONE_CONFIG_GDRIVE_TEAM_DRIVE_3}
            - RCLONE_CONFIG_GDRIVE_WOLF_TEAM_DRIVE=${RCLONE_CONFIG_GDRIVE_TEAM_DRIVE_3}
            - MERGED_DEST=/mnt/secure_media3
        env_file: 
            - "${DOCKER_ROOT}/config/rclone.env"
        volumes:
            - '${DOCKER_ROOT}/rclone/:/config:rw'
            - '${DOCKER_ROOT}/mnt/rclone:/mnt:shared'
        networks:
            - bridge
            - internal
        ports:
            - "15573:5574"
        logging:
            options:
                max-size: 20m
        devices:
            - /dev/fuse
        cap_add:
            - SYS_ADMIN
        security_opt:
            - apparmor:unconfined
        image: slink42/rclone
    plexdrive1:
        restart: always
        labels:
            - "autoheal=true"
        environment:
            - TZ=Australia/Melbourne
            - PUID=${USERID}
            - PGID=${GROUPID}
            - 'PLEXDRIVE_OPTS=-v 2 --max-chunks=10 --chunk-size=20M --chunk-check-threads=20 --chunk-load-threads=4 --chunk-load-ahead=5 --drive-id=${RCLONE_CONFIG_GDRIVE_TEAM_DRIVE_1} -o allow_other,read_only,nonempty,auto_unmount'
        env_file: 
            - "${DOCKER_ROOT}/config/rclone.env"
        volumes:
            - '${DOCKER_ROOT}/plexdrive/config:/config:rw'
            - '${DOCKER_ROOT}/mnt/plexdrive/secure_media:/data:shared'
        networks:
            - bridge
            - internal
        logging:
            options:
                max-size: 20m
        devices:
            - /dev/fuse
        cap_add:
            - SYS_ADMIN
        security_opt:
            - apparmor:unconfined
        image: 'wiserain/plexdrive'
    rclone_plexdrive1:
        restart: always
        labels:
            - "autoheal=true"
        environment:
            - TZ=Australia/Melbourne
            - PGID=${GROUPID}
            - PUID=${USERID}
            #- RCLONE_LOG_FILE=/config/rclone_plexdrive1_mount.log
            - RCLONE_LOG_LEVEL=INFO
            - 'RCLONE_REMOTE_PATH=plexdrive_securemedia_crypt:'
            - 'RCLONE_MOUNT_USER_OPTS=--include=mountcheck --include=Media/tv-4k/** --include=Media/movies-4k/** --read-only --use-json-log --dir-cache-time 30m --multi-thread-streams=20 --allow-non-empty --allow-other --rc-web-gui --rc-web-gui-no-open-browser --rc-user ${RCLONE_USER} --rc-pass ${RCLONE_PASSWORD}'
            - MERGED_DEST=/mnt/rclone/plexdrive_secure_media
        env_file: 
            - "${DOCKER_ROOT}/config/rclone.env"
        volumes:
            - '${DOCKER_ROOT}/rclone/:/config:rw'
            - '${DOCKER_ROOT}/mnt/plexdrive:/mnt/plexdrive:slave'
            - '${DOCKER_ROOT}/mnt/rclone:/mnt/rclone:shared'
        networks:
            - bridge
            - internal
        ports:
            - "15574:5574"
        logging:
            options:
                max-size: 20m
        devices:
            - /dev/fuse
        cap_add:
            - SYS_ADMIN
        security_opt:
            - apparmor:unconfined
        image: slink42/rclone
        depends_on:
            plexdrive1:
                condition: service_healthy
    # plexdrive2:
    #     restart: always
    #     labels:
    #         - "autoheal=true"
    #     environment:
    #         - TZ=Australia/Melbourne
    #         - PUID=${USERID}
    #         - PGID=${GROUPID}
    #         - 'PLEXDRIVE_OPTS=-v 2 --max-chunks=10 --chunk-size=20M --chunk-check-threads=20 --chunk-load-threads=4 --chunk-load-ahead=5 --cache-file=/config/cache2.bolt --drive-id=${RCLONE_CONFIG_GDRIVE_TEAM_DRIVE_2} -o allow_other,read_only,nonempty,auto_unmount'
    #     env_file: 
    #         - "${DOCKER_ROOT}/config/rclone.env"
    #     volumes:
    #         - '${DOCKER_ROOT}/plexdrive/config:/config:rw'
    #         - '${DOCKER_ROOT}/mnt/plexdrive/secure_media2:/data:shared'
    #     networks:
    #         - bridge
    #         - internal
    #     logging:
    #         options:
    #             max-size: 20m
    #     devices:
    #         - /dev/fuse
    #     cap_add:
    #         - SYS_ADMIN
    #     security_opt:
    #         - apparmor:unconfined
    #     image: 'wiserain/plexdrive'
    # rclone_plexdrive2:
    #     restart: always
    #     labels:
    #         - "autoheal=true"
    #     environment:
    #         - TZ=Australia/Melbourne
    #         - PGID=${GROUPID}
    #         - PUID=${USERID}
    #         #- RCLONE_LOG_FILE=/config/rclone_plexdrive2_mount.log
    #         - RCLONE_LOG_LEVEL=INFO
    #         - 'RCLONE_REMOTE_PATH=plexdrive_securemedia2_crypt:'
    #         - 'RCLONE_MOUNT_USER_OPTS=--include=mountcheck --include=Media/tv-4k/** --include=Media/movies-4k/** --read-only --use-json-log --dir-cache-time 30m --multi-thread-streams=20 --allow-non-empty --allow-other --rc-web-gui --rc-web-gui-no-open-browser --rc-user ${RCLONE_USER} --rc-pass ${RCLONE_PASSWORD}'
    #         - MERGED_DEST=/mnt/rclone/plexdrive_secure_media2
    #     env_file: 
    #         - "${DOCKER_ROOT}/config/rclone.env"
    #     volumes:
    #         - '${DOCKER_ROOT}/rclone/:/config:rw'
    #         - '${DOCKER_ROOT}/mnt/plexdrive:/mnt/plexdrive:slave'
    #         - '${DOCKER_ROOT}/mnt/rclone:/mnt/rclone:shared'
    #     networks:
    #         - bridge
    #         - internal
    #     ports:
    #         - "15575:5574"
    #     logging:
    #         options:
    #             max-size: 20m
    #     devices:
    #         - /dev/fuse
    #     cap_add:
    #         - SYS_ADMIN
    #     security_opt:
    #         - apparmor:unconfined
    #     image: slink42/rclone
    #     depends_on:
    #         plexdrive2:
    #             condition: service_healthy
    plexdrive3:
        restart: always
        labels:
            - "autoheal=true"
        environment:
            - TZ=Australia/Melbourne
            - PUID=${USERID}
            - PGID=${GROUPID}
            - 'PLEXDRIVE_OPTS=-v 2 --max-chunks=10 --chunk-size=20M --chunk-check-threads=20 --chunk-load-threads=4 --chunk-load-ahead=5 --cache-file=/config/cache3.bolt --drive-id=${RCLONE_CONFIG_GDRIVE_TEAM_DRIVE_3} -o allow_other,read_only,nonempty,auto_unmount'
        env_file: 
            - "${DOCKER_ROOT}/config/rclone.env"
        volumes:
            - '${DOCKER_ROOT}/plexdrive/config:/config:rw'
            - '${DOCKER_ROOT}/mnt/plexdrive/secure_media3:/data:shared'
        networks:
            - bridge
            - internal
        logging:
            options:
                max-size: 20m
        devices:
            - /dev/fuse
        cap_add:
            - SYS_ADMIN
        security_opt:
            - apparmor:unconfined
        image: 'wiserain/plexdrive'
    rclone_plexdrive3:
        restart: always
        labels:
            - "autoheal=true"
        environment:
            - TZ=Australia/Melbourne
            - PGID=${GROUPID}
            - PUID=${USERID}
            #- RCLONE_LOG_FILE=/config/rclone_plexdrive3_mount.log
            - RCLONE_LOG_LEVEL=INFO
            - 'RCLONE_REMOTE_PATH=plexdrive_securemedia3_crypt:'
            - 'RCLONE_MOUNT_USER_OPTS=--include=mountcheck --include=Media/tv-4k/** --include=Media/movies-4k/** --read-only --use-json-log --dir-cache-time 30m --multi-thread-streams=20 --allow-non-empty --allow-other --rc-web-gui --rc-web-gui-no-open-browser --rc-user ${RCLONE_USER} --rc-pass ${RCLONE_PASSWORD}'
            - MERGED_DEST=/mnt/rclone/plexdrive_secure_media3
        env_file: 
            - "${DOCKER_ROOT}/config/rclone.env"
        volumes:
            - '${DOCKER_ROOT}/rclone/:/config:rw'
            - '${DOCKER_ROOT}/mnt/plexdrive:/mnt/plexdrive:slave'
            - '${DOCKER_ROOT}/mnt/rclone:/mnt/rclone:shared'
        networks:
            - bridge
            - internal
        ports:
            - "15576:5574"
        logging:
            options:
                max-size: 20m
        devices:
            - /dev/fuse
        cap_add:
            - SYS_ADMIN
        security_opt:
            - apparmor:unconfined
        image: slink42/rclone
        depends_on:
            plexdrive3:
                condition: service_healthy
    streamer_mergerfs:
        restart: always
        labels:
            - "autoheal=true"
        environment:
            - TZ=Australia/Melbourne
            - PUID=${USERID}
            - PGID=${GROUPID}
            - MFS_USER_OPTS=allow_other,nonempty,auto_cache,auto_unmount,direct_io,gid=${GROUPID},sync_read,uid=${USERID}
            - MFS_BRANCHES=/mnt/rclone/plexdrive_secure_media/=RO:/mnt/rclone/plexdrive_secure_media2/=RO:/mnt/rclone/plexdrive_secure_media3/=RO:/mnt/rclone/secure_media=RO:/mnt/rclone/secure_media2=RO:/mnt/rclone/secure_media3=RO
            - MERGED_DEST=/mnt/mergerfs/streamer/media
            # - 'HEALTHCHECK_PATHS=/mnt/mergerfs/streamer/media/mountcheck /mnt/mergerfs/streamer/media/Media/movies /mnt/mergerfs/streamer/media/Media/movies-4k /mnt/mergerfs/streamer/media/Media/tv /mnt/mergerfs/streamer/media/Media/tv-4k'
        volumes:
            - '${DOCKER_ROOT}/mnt/mergerfs:/mnt/mergerfs:shared'
            - '${DOCKER_ROOT}/mnt/rclone:/mnt/rclone:rslave'
        networks:
            - internal
        logging:
            options:
                max-size: 20m
        devices:
            - /dev/fuse
        cap_add:
            - SYS_ADMIN
        security_opt:
            - apparmor:unconfined
        image: slink42/mergerfs
    plex_streamer:
        network_mode: host
        # networks:
        #     - bridge
        #     - internal
        restart: always
        labels:
            - "autoheal=true"
        environment:
            - TZ=Australia/Melbourne
            - HOST_OS=Unraid
            - PLEX_CLAIM=${PLEX_CLAIM}
            - PLEX_UID=${USERID}
            - PLEX_GID=${GROUPID}
            - VERSION=latest
            - 'NVIDIA_VISIBLE_DEVICES='
            - TCP_PORT_32400=32400
            - TCP_PORT_3005=3005
            - TCP_PORT_8324=8324
            - TCP_PORT_32469=32469
            - UDP_PORT_1900=1900
            - UDP_PORT_32410=32410
            - UDP_PORT_32412=32412
            - UDP_PORT_32413=32413
            - UDP_PORT_32414=32414
            - PUID=${USERID}
            - PGID=${GROUPID}
            - LOAD_LIBRARY_DB_TO_MEMORY=${LOAD_LIBRARY_DB_TO_MEMORY}
            - 'SCANNER_LIBRARY_PATH=/mnt/plex-scanner/Library/Application Support/Plex Media Server'
            - 'HEALTHCHECK_MOUNTS=/plex/media'
            - 'HEALTHCHECK_PATHS=/plex/media/mountcheck'
            - 'LIB_BACKUP_PATH_MASTER=/backups/databases'
            - 'LIB_BACKUP_PATH_LOCAL=/config/Library/Application Support/Plex Media Server/Plug-in Support/Databases'
            - 'LIB_RELOAD_CRON=35 5 * * *'
            - 'LIB_META_BACKUP_PATH_MASTER=/backups/meta'
        volumes:
            - '${DOCKER_ROOT}/plex-streamer/transcode:/transcode:rw'
            - '${DOCKER_ROOT}/mnt/mergerfs/streamer:/plex:slave'
            - '${DOCKER_ROOT}/plex-streamer/:/config:rw'
            # - '${DOCKER_ROOT}/plex-streamer/custom-scripts:/custom-cont-init.d:ro'
            # - '${DOCKER_ROOT}/plex-streamer/custom-services:/custom-services.d:ro'
            - '${DOCKER_ROOT}/plex-scanner/:/mnt/plex-scanner:rw'
            - '${DOCKER_ROOT}/plex-scanner/Library/Application Support/Plex Media Server/Plug-in Support/Databases/:/backups/databases:rw'
            - '${LARGE_DISK_ROOT}/plex_library_backup/meta:/backups/meta:rw'
            - '${LARGE_DISK_ROOT}/tmp:/tmp:rw'
        tmpfs:
            - /ram_disk
        ports:
            - "32400:32400"
        image: slink42/plex
        # depends_on:
        #     streamer_mergerfs:
        #         condition: service_healthy
    autoheal:
        image: willfarrell/autoheal
        environment:
            - AUTOHEAL_CONTAINER_LABEL=autoheal
            - AUTOHEAL_INTERVAL=5
            - DOCKER_SOCK=/var/run/docker.sock
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        networks:
            - internal
        restart: always
    watchtower:
        image: containrrr/watchtower
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        command: --interval 30 --include-stopped
        restart: always

volumes:
    empty_volume: