version: '3.3'
services:
    rclone_media_scanner1:
        restart: always
        labels:
            - "autoheal=true"
        environment:
            - TZ=Australia/Melbourne
            - PGID=${GROUPID}
            - PUID=${USERID}
            - 'HEALTHCHECK_MOUNTS=/mnt/scanner_secure_media'
            - 'HEALTHCHECK_PATHS=/mnt/scanner_secure_media/mountcheck'
            #- RCLONE_LOG_FILE=/config/rclone_media_scanner_mount_1.log
            - RCLONE_LOG_LEVEL=INFO
            - 'RCLONE_REMOTE_PATH=secure_media_scanner:'
            - 'RCLONE_MOUNT_USER_OPTS=--read-only --use-json-log --acd-templink-threshold 1g --buffer-size 8M --timeout 5s --contimeout 5s --stats 300s --dir-cache-time 30m --multi-thread-streams=20 --allow-non-empty --allow-other --rc-web-gui --rc-web-gui-no-open-browser --rc-user ${RCLONE_USER} --rc-pass ${RCLONE_PASSWORD}'
            - RCLONE_CONFIG_GDRIVE_MOLE_TEAM_DRIVE=${RCLONE_CONFIG_GDRIVE_TEAM_DRIVE_1}
            - RCLONE_CONFIG_GDRIVE_WOLF_TEAM_DRIVE=${RCLONE_CONFIG_GDRIVE_TEAM_DRIVE_1}
            - MERGED_DEST=/mnt/scanner_secure_media
        volumes:
            - '${DOCKER_ROOT}/rclone/:/config:rw'
            - '${DOCKER_ROOT}/scripts/:/scripts:ro'
            - '${DOCKER_ROOT}/mnt/rclone:/mnt:rshared'
        networks:
            - bridge
            - internal
        ports:
            - "25571:5574"
        logging:
            options:
                max-size: 20m
        devices:
            - /dev/fuse
        cap_add:
            - SYS_ADMIN
        security_opt:
            - apparmor:unconfined
        image: slink42/rclone
        healthcheck:
            test: ["CMD-SHELL", "sh /scripts/healthcheck"]
            interval: 120s
            timeout: 10s
            retries: 1
            start_period: 5s
    rclone_media_scanner2:
        restart: always
        labels:
            - "autoheal=true"
        environment:
            - TZ=Australia/Melbourne
            - PGID=${GROUPID}
            - PUID=${USERID}
            - 'HEALTHCHECK_MOUNTS=/mnt/scanner_secure_media2'
            - 'HEALTHCHECK_PATHS=/mnt/scanner_secure_media2'
            #- RCLONE_LOG_FILE=/config/rclone_media_scanner_mount_2.log
            - RCLONE_LOG_LEVEL=INFO
            - 'RCLONE_REMOTE_PATH=secure_media_scanner:'
            - 'RCLONE_MOUNT_USER_OPTS=--read-only --use-json-log --acd-templink-threshold 1g --buffer-size 8M --timeout 5s --contimeout 5s --stats 300s --dir-cache-time 30m --multi-thread-streams=20 --allow-non-empty --allow-other --rc-web-gui --rc-web-gui-no-open-browser --rc-user ${RCLONE_USER} --rc-pass ${RCLONE_PASSWORD}'
            - RCLONE_CONFIG_GDRIVE_MOLE_TEAM_DRIVE=${RCLONE_CONFIG_GDRIVE_TEAM_DRIVE_2}
            - RCLONE_CONFIG_GDRIVE_WOLF_TEAM_DRIVE=${RCLONE_CONFIG_GDRIVE_TEAM_DRIVE_2}
            - MERGED_DEST=/mnt/scanner_secure_media2
        volumes:
            - '${DOCKER_ROOT}/rclone/:/config:rw'
            - '${DOCKER_ROOT}/scripts/:/scripts:ro'
            - '${DOCKER_ROOT}/mnt/rclone:/mnt:rshared'
        networks:
            - bridge
            - internal
        ports:
            - "25572:5574"
        logging:
            options:
                max-size: 20m
        devices:
            - /dev/fuse
        cap_add:
            - SYS_ADMIN
        security_opt:
            - apparmor:unconfined
        image: slink42/rclone
        healthcheck:
            test: ["CMD-SHELL", "sh /scripts/healthcheck"]
            interval: 120s
            timeout: 10s
            retries: 1
            start_period: 5s
    rclone_media_scanner3:
        restart: always
        labels:
            - "autoheal=true"
        environment:
            - TZ=Australia/Melbourne
            - PGID=${GROUPID}
            - PUID=${USERID}
            - 'HEALTHCHECK_MOUNTS=/mnt/scanner_secure_media3'
            - 'HEALTHCHECK_PATHS=/mnt/scanner_secure_media3'
            #- RCLONE_LOG_FILE=/config/rclone_media_scanner_mount_3.log
            - RCLONE_LOG_LEVEL=INFO
            - 'RCLONE_REMOTE_PATH=secure_media_scanner:'
            - 'RCLONE_MOUNT_USER_OPTS=--read-only --use-json-log --acd-templink-threshold 1g --buffer-size 8M --timeout 5s --contimeout 5s --stats 300s --dir-cache-time 30m --multi-thread-streams=20 --allow-non-empty --allow-other --rc-web-gui --rc-web-gui-no-open-browser --rc-user ${RCLONE_USER} --rc-pass ${RCLONE_PASSWORD}'
            - RCLONE_CONFIG_GDRIVE_MOLE_TEAM_DRIVE=${RCLONE_CONFIG_GDRIVE_TEAM_DRIVE_3}
            - RCLONE_CONFIG_GDRIVE_WOLF_TEAM_DRIVE=${RCLONE_CONFIG_GDRIVE_TEAM_DRIVE_3}
            - MERGED_DEST=/mnt/scanner_secure_media3
        volumes:
            - '${DOCKER_ROOT}/rclone/:/config:rw'
            - '${DOCKER_ROOT}/scripts/:/scripts:ro'
            - '${DOCKER_ROOT}/mnt/rclone:/mnt:rshared'
        networks:
            - bridge
            - internal
        ports:
            - "25573:5574"
        logging:
            options:
                max-size: 20m
        devices:
            - /dev/fuse
        cap_add:
            - SYS_ADMIN
        security_opt:
            - apparmor:unconfined
        image: slink42/rclone
        healthcheck:
            test: ["CMD-SHELL", "sh /scripts/healthcheck"]
            interval: 120s
            timeout: 10s
            retries: 1
            start_period: 5s
    scanner_mergerfs:
        restart: always
        labels:
            - "autoheal=true"
        environment:
            - TZ=Australia/Melbourne
            - PUID=${USERID}
            - PGID=${GROUPID}
            - MFS_USER_OPTS=allow_other,nonempty,auto_cache,auto_unmount,direct_io,gid=${GROUPID},sync_read,uid=${USERID}
            - MFS_BRANCHES=/mnt/rclone/secure_media=RO:/mnt/rclone/secure_media2=RO:/mnt/rclone/secure_media3=RO
            - MERGED_DEST=/mnt/mergerfs/scanner/media
            - 'HEALTHCHECK_MOUNTS=/mnt/mergerfs/scanner/media'
            - 'HEALTHCHECK_PATHS=/mnt/mergerfs/scanner/media/mountcheck /mnt/mergerfs/scanner/media/Media/movies /mnt/mergerfs/scanner/media/Media/movies-4k /mnt/mergerfs/scanner/media/Media/tv /mnt/mergerfs/scanner/media/Media/tv-4k'
        volumes:
            - '${DOCKER_ROOT}/mnt/mergerfs:/mnt/mergerfs:rshared'
            - '${DOCKER_ROOT}/mnt/rclone:/mnt/rclone:rslave'
            - '${DOCKER_ROOT}/scripts/:/scripts:ro'
        networks:
            - internal
        logging:
            options:
                max-size: 20m
        devices:
            - /dev/fuse
        cap_add:
            - SYS_ADMIN
        security_opt:
            - apparmor:unconfined
        image: slink42/mergerfs
        healthcheck:
            test: ["CMD-SHELL", "sh /scripts/healthcheck"]
            interval: 60s
            timeout: 55s
            retries: 3
            start_period: 10s
    plex_scanner:
        networks:
            - bridge
            - internal
        restart: always
        labels:
            - "autoheal=true"
        environment:
            - TZ=Australia/Melbourne
            - PLEX_CLAIM=${PLEX_CLAIM}
            - PLEX_UID=${USERID}   
            - PLEX_GID=${GROUPID}
            - VERSION=latest
            - 'NVIDIA_VISIBLE_DEVICES='
            - PUID=${USERID}   
            - PGID=${GROUPID}
            - 'HEALTHCHECK_MOUNTS=/plex/media'
            - 'HEALTHCHECK_PATHS=/plex/media/mountcheck'
        volumes:
            - '${DOCKER_ROOT}/mnt/mergerfs/scanner:/plex:rslave' # should contain subfolder: media
            - '${DOCKER_ROOT}/plex-scanner/:/config:rw'
            - '${DOCKER_ROOT}/scripts/:/scripts:ro'
        ports:
            - "34400:32400"
        image: linuxserver/plex
        healthcheck:
            test: ["CMD-SHELL", "bash /scripts/plexhealthcheck"]
            interval: 300s
            timeout: 60s
            retries: 3
            start_period: 30s
        # depends_on:
        #     scanner_mergerfs:
        #         condition: service_healthy
    plex-meta-manager:
        image: lscr.io/linuxserver/plex-meta-manager:latest
        environment:
            - TZ=Australia/Melbourne
            - PLEX_UID=${USERID}   
            - PLEX_GID=${GROUPID}
            - PMM_CONFIG=/config/config.yml #optional
            - PMM_TIME=03:00 #optional
            - PMM_RUN=True #optional
            - PMM_TEST=False #optional
            - PMM_NO_MISSING=False #optional
            - PMM_DELETE_COLLECTIONS=False #optional
            - UMASK=022
        volumes:
            - '${DOCKER_ROOT}/plex-meta-manager:/config'
        restart: always
        networks:
            - bridge
            - internal