version: '3.3'
services:
    pushgateway:
        image: docker.io/prom/pushgateway
        networks:
            - internal
        hostname: pushgateway
        restart: unless-stopped
    prometheus:
        image: docker.io/prom/prometheus
        ports:
            - "19090:9090"
        networks:
            - bridge
            - internal
        hostname: prometheus
        volumes:
            - ${DOCKER_ROOT}/prometheus:/etc/prometheus
        restart: unless-stopped
    exporter:
        image: docker.io/vshn/rclone-exporter:v1
        command:
            - --push.url
            - http://pushgateway:9091
            - --scrape.url
            - http://plexdriveplus-rclone_media-1:5572
        # Example of configuring Basic Auth and other options with ENV vars
        environment:
            PUSH_INTERVAL: 15s
            LOG_LEVEL: debug
            SCRAPE_BASICAUTH_USERNAME: ${RCLONE_USER}
            SCRAPE_BASICAUTH_PASSWORD: ${RCLONE_PASSWORD}
        networks:
            - internal
        hostname: exporter
        restart: unless-stopped
    heimdall:
        image: lscr.io/linuxserver/heimdall:latest
        environment:
            - PGID=${GROUPID}
            - PUID=${USERID} 
            - TZ=Australia/Melbourne
        volumes:
            - ${DOCKER_ROOT}/heimdall:/config
        ports:
            - 8889:80
            - 4444:443
        networks:
            - bridge
            - internal
        hostname: heimdall
        restart: always
    nginx-proxy-manager:
        image: 'jc21/nginx-proxy-manager:latest'
        hostname: nginx-proxy-manager
        restart: always
        ports:
            # These ports are in format <host-port>:<container-port>
            - '8800:80' # Public HTTP Port
            - '443:443' # Public HTTPS Port
            - '81:81' # Admin Web Port
            # Add any other Stream port you want to expose
            # - '21:21' # FTP

        # Uncomment the next line if you uncomment anything in the section
        # environment:
        # Uncomment this if you want to change the location of 
        # the SQLite DB file within the container
        # DB_SQLITE_FILE: "/data/database.sqlite"

        # Uncomment this if IPv6 is not enabled on your host
        # DISABLE_IPV6: 'true'

        volumes:
            - ${DOCKER_ROOT}/nginx-proxy-manager:/data
        networks:
            - bridge
            - internal
            - support
