version: '3.3'
networks:
    internal:
        internal: true
    bridge:
        driver: bridge
services:
    rclone_media1:
        restart: always
        labels:
            - "autoheal=true"
        environment:
            - TZ=Australia/Melbourne
            - PGID=${GROUPID}
            - PUID=${USERID}
            - 'HEALTHCHECK_MOUNTS=/data'
            - 'HEALTHCHECK_PATHS=/data/mountcheck'
            #- RCLONE_LOG_FILE=/config/rclone_media_mount_1.log
            - RCLONE_LOG_LEVEL=INFO
            - 'RCLONE_REMOTE_PATH=secure_media:'
            - 'RCLONE_MOUNT_USER_OPTS=--read-only --use-json-log --acd-templink-threshold 1g --buffer-size 8M --timeout 5s --contimeout 5s --stats 300s --dir-cache-time 30m --multi-thread-streams=20 --allow-non-empty --allow-other --rc-web-gui --rc-web-gui-update --rc-web-gui-no-open-browser --rc-user ${RCLONE_USER} --rc-pass ${RCLONE_PASSWORD}'
            - RCLONE_CONFIG_GDRIVE_MOLE_TEAM_DRIVE=${RCLONE_CONFIG_GDRIVE_TEAM_DRIVE_1}
            - RCLONE_CONFIG_GDRIVE_WOLF_TEAM_DRIVE=${RCLONE_CONFIG_GDRIVE_TEAM_DRIVE_1}
        volumes:
            - '${DOCKER_ROOT}/rclone/:/config:rw'
            - '${DOCKER_ROOT}/scripts/:/scripts:ro'
            - '${DOCKER_ROOT}/mnt/rclone/secure_media:/data:rshared'
            - empty_volume:/local
        networks:
            - bridge
            - internal
        ports:
            - "15571:5574"
        logging:
            options:
                max-size: 20m
        devices:
            - /dev/fuse
        cap_add:
            - SYS_ADMIN
        security_opt:
            - apparmor:unconfined
        image: wiserain/rclone
        healthcheck:
            test: ["CMD-SHELL", "sh /scripts/healthcheck"]
            interval: 120s
            timeout: 10s
            retries: 1
            start_period: 5s
    rclone_media2:
        restart: always
        labels:
            - "autoheal=true"
        environment:
            - TZ=Australia/Melbourne
            - PGID=${GROUPID}
            - PUID=${USERID}
            - 'HEALTHCHECK_MOUNTS=/data'
            - 'HEALTHCHECK_PATHS=/data'
            #- RCLONE_LOG_FILE=/config/rclone_media_mount_2.log
            - RCLONE_LOG_LEVEL=INFO
            - 'RCLONE_REMOTE_PATH=secure_media:'
            - 'RCLONE_MOUNT_USER_OPTS=--read-only --use-json-log --acd-templink-threshold 1g --buffer-size 8M --timeout 5s --contimeout 5s --stats 300s --dir-cache-time 30m --multi-thread-streams=20 --allow-non-empty --allow-other --rc-web-gui --rc-web-gui-update --rc-web-gui-no-open-browser --rc-user ${RCLONE_USER} --rc-pass ${RCLONE_PASSWORD}'
            - RCLONE_CONFIG_GDRIVE_MOLE_TEAM_DRIVE=${RCLONE_CONFIG_GDRIVE_TEAM_DRIVE_2}
            - RCLONE_CONFIG_GDRIVE_WOLF_TEAM_DRIVE=${RCLONE_CONFIG_GDRIVE_TEAM_DRIVE_2}
        volumes:
            - '${DOCKER_ROOT}/rclone/:/config:rw'
            - '${DOCKER_ROOT}/scripts/:/scripts:ro'
            - '${DOCKER_ROOT}/mnt/rclone/secure_media2:/data:rshared'
            - empty_volume:/local
        networks:
            - bridge
            - internal
        ports:
            - "15572:5574"
        logging:
            options:
                max-size: 20m
        devices:
            - /dev/fuse
        cap_add:
            - SYS_ADMIN
        security_opt:
            - apparmor:unconfined
        image: wiserain/rclone
        healthcheck:
            test: ["CMD-SHELL", "sh /scripts/healthcheck"]
            interval: 120s
            timeout: 10s
            retries: 1
            start_period: 5s
    rclone_media3:
        restart: always
        labels:
            - "autoheal=true"
        environment:
            - TZ=Australia/Melbourne
            - PGID=${GROUPID}
            - PUID=${USERID}
            - 'HEALTHCHECK_MOUNTS=/data'
            - 'HEALTHCHECK_PATHS=/data'
            - RCLONE_LOG_FILE=/config/rclone_media_mount_3.log
            - RCLONE_LOG_LEVEL=INFO
            - 'RCLONE_REMOTE_PATH=secure_media:'
            - 'RCLONE_MOUNT_USER_OPTS=--read-only --use-json-log --acd-templink-threshold 1g --buffer-size 8M --timeout 5s --contimeout 5s --stats 300s --dir-cache-time 30m --multi-thread-streams=20 --allow-non-empty --allow-other --rc-web-gui --rc-web-gui-update --rc-web-gui-no-open-browser --rc-user ${RCLONE_USER} --rc-pass ${RCLONE_PASSWORD}'
            - RCLONE_CONFIG_GDRIVE_MOLE_TEAM_DRIVE=${RCLONE_CONFIG_GDRIVE_TEAM_DRIVE_3}
            - RCLONE_CONFIG_GDRIVE_WOLF_TEAM_DRIVE=${RCLONE_CONFIG_GDRIVE_TEAM_DRIVE_3}
        volumes:
            - '${DOCKER_ROOT}/rclone/:/config:rw'
            - '${DOCKER_ROOT}/scripts/:/scripts:ro'
            - '${DOCKER_ROOT}/mnt/rclone/secure_media3:/data:rshared'
            - empty_volume:/local
        networks:
            - bridge
            - internal
        ports:
            - "15573:5574"
        logging:
            options:
                max-size: 20m
        devices:
            - /dev/fuse
        cap_add:
            - SYS_ADMIN
        security_opt:
            - apparmor:unconfined
        image: wiserain/rclone
        healthcheck:
            test: ["CMD-SHELL", "sh /scripts/healthcheck"]
            interval: 120s
            timeout: 10s
            retries: 1
            start_period: 5s
    plexdrive:
        restart: always
        labels:
            - "autoheal=true"
        environment:
            - TZ=Australia/Melbourne
            - PUID=${USERID}
            - PGID=${GROUPID}
            - 'HEALTHCHECK_MOUNTS=/data'
            - HEALTHCHECK_PATHS=/data /data/Config
            - POOLING_FS=mergerfs
            - 'PLEXDRIVE_OPTS=-v 2 --max-chunks=10 --chunk-size=20M --chunk-check-threads=20 --chunk-load-threads=4 --chunk-load-ahead=5 --drive-id=0ALNBa0QBHhldUk9PVA -o allow_other,read_only,nonempty,auto_unmount'
            # - MFS_USER_OPTS=rw,use_ino,func.getattr=newest,category.action=all,category.create=ff,cache.files=auto-full,dropcacheonclose=true
        volumes:
            - '${DOCKER_ROOT}/plexdrive/config:/config:rw'
            - '${DOCKER_ROOT}/scripts/:/scripts:ro'
            - '${DOCKER_ROOT}/plexdrive/cache:/cache:rw'
            - '${DOCKER_ROOT}/mnt/plexdrive/secure_media:/data:rshared'
            - '${DOCKER_ROOT}/mnt/plexdrive/cloud:/cloud:rshared'
            - empty_volume:/local
        networks:
            - bridge
            - internal
        logging:
            options:
                max-size: 20m
        devices:
            - /dev/fuse
        cap_add:
            - SYS_ADMIN
        security_opt:
            - apparmor:unconfined
        image: 'wiserain/plexdrive'
        healthcheck:
            test: ["CMD-SHELL", "sh /scripts/healthcheck"]
            interval: 30s
            timeout: 25s
            retries: 5
            start_period: 20s
    rclone_plexdrive:
        restart: always
        labels:
            - "autoheal=true"
        environment:
            - TZ=Australia/Melbourne
            - PGID=${GROUPID}
            - PUID=${USERID}
            - 'HEALTHCHECK_MOUNTS=/data'
            - 'HEALTHCHECK_PATHS=/data/mountcheck'
            #- RCLONE_LOG_FILE=/config/rclone_plexdrive_mount.log
            - RCLONE_LOG_LEVEL=INFO
            - 'RCLONE_REMOTE_PATH=plexdrive_crypt:'
            - 'RCLONE_MOUNT_USER_OPTS=--read-only --use-json-log --dir-cache-time 30m --multi-thread-streams=20 --allow-non-empty --allow-other --rc-web-gui --rc-web-gui-update --rc-web-gui-no-open-browser --rc-user ${RCLONE_USER} --rc-pass ${RCLONE_PASSWORD}'
        volumes:
            - '${DOCKER_ROOT}/rclone/:/config:rw'
            - '${DOCKER_ROOT}/scripts/:/scripts:ro'
            - '${DOCKER_ROOT}/mnt/plexdrive/secure_media/:/mnt/plexdrive'
            - '${DOCKER_ROOT}/mnt/rclone/plexdrive_secure_media:/data:rshared'
            - empty_volume:/local
        networks:
            - bridge
            - internal
        ports:
            - "15574:5574"
        logging:
            options:
                max-size: 20m
        devices:
            - /dev/fuse
        cap_add:
            - SYS_ADMIN
        security_opt:
            - apparmor:unconfined
        image: wiserain/rclone
        healthcheck:
            test: ["CMD-SHELL", "sh /scripts/healthcheck"]
            interval: 120s
            timeout: 10s
            retries: 1
            start_period: 5s
        depends_on:
            plexdrive:
                condition: service_healthy
    streamer_mergerfs:
        entrypoint: /bin/sh
        command: /scripts/mergerfs/start.sh
        restart: always
        labels:
            - "autoheal=true"
        environment:
            - TZ=Australia/Melbourne
            - PUID=${USERID}
            - PGID=${GROUPID}
            - MFS_USER_OPTS=allow_other,auto_cache,auto_unmount,direct_io,gid=${GROUPID},sync_read,uid=${USERID}
            - MFS_BRANCHES=/mnt/plexdrive/secure_media/=RO:/mnt/rclone/secure_media=RO:/mnt/rclone/secure_media2=RO:/mnt/rclone/secure_media3=RO
            - MFS_DEST=/data/media
            - 'HEALTHCHECK_MOUNTS=/data/media'
            - 'HEALTHCHECK_PATHS=/data/media/mountcheck /data/media/Media/movies /data/media/Media/movies-4k /data/media/Media/tv /data/media/Media/tv-4k'
        volumes:
            - '${DOCKER_ROOT}/mnt/mergerfs/streamer:/data:rshared'
            - '${DOCKER_ROOT}/mnt/rclone:/mnt/rclone:rslave'
            - '${DOCKER_ROOT}/mnt/rclone/plexdrive_secure_media/Media/movies-4k/:/mnt/plexdrive/secure_media/Media/movies-4k/:rslave'
            - '${DOCKER_ROOT}/mnt/rclone/plexdrive_secure_media/Media/tv-4k/:/mnt/plexdrive/secure_media/Media/tv-4k/:rslave'
            - '${DOCKER_ROOT}/scripts/:/scripts:ro'
        networks:
            - internal
        logging:
            options:
                max-size: 20m
        devices:
            - /dev/fuse
        cap_add:
            - SYS_ADMIN
        security_opt:
            - apparmor:unconfined
        image: hotio/mergerfs
        healthcheck:
            test: ["CMD-SHELL", "sh /scripts/healthcheck"]
            interval: 60s
            timeout: 55s
            retries: 3
            start_period: 10s
    plex_streamer:
        network_mode: host
        networks:
            - bridge
            - internal
        restart: unless-stopped
        labels:
            - "autoheal=true"
        environment:
            - TZ=Australia/Melbourne
            - HOST_OS=Unraid
            - PLEX_CLAIM=${PLEX_CLAIM}
            - PLEX_UID=${USERID}
            - PLEX_GID=${GROUPID}
            - VERSION=latest
            - 'NVIDIA_VISIBLE_DEVICES='
            - 'SCANNER_LIBRARY_PATH=/mnt/plex-scanner/Library/Application Support/Plex Media Server'
            - 'STREAMER_LIBRARY_PATH=/mnt/plex-streamer/Library/Application Support/Plex Media Server'
            - TCP_PORT_32400=32400
            - TCP_PORT_3005=3005
            - TCP_PORT_8324=8324
            - TCP_PORT_32469=32469
            - UDP_PORT_1900=1900
            - UDP_PORT_32410=32410
            - UDP_PORT_32412=32412
            - UDP_PORT_32413=32413
            - UDP_PORT_32414=32414
            - PUID=${USERID}
            - PGID=${GROUPID}
            - OPTIMISE_LIBRARY=NO_DB_CLEAN # Any value is fine here.
            - 'HEALTHCHECK_MOUNTS=/plex/media'
            - 'HEALTHCHECK_PATHS=/plex/media/mountcheck'
        volumes:
            - '${DOCKER_ROOT}/plex-streamer/transcode:/transcode:rw'
            - '${DOCKER_ROOT}/mnt/mergerfs/streamer:/plex:rslave'
            - '${DOCKER_ROOT}/plex-scanner/:/mnt/plex-scanner:rw'
            - '${DOCKER_ROOT}/plex-streamer/:/config:rw'
            - '${DOCKER_ROOT}/scripts/:/scripts:ro'
        ports:
            - "32400:32400"
        image: linuxserver/plex
        healthcheck:
            test: ["CMD-SHELL", "bash /scripts/plexhealthcheck"]
            interval: 300s
            timeout: 60s
            retries: 3
            start_period: 30s
        # depends_on:
        #     streamer_mergerfs:
        #         condition: service_healthy
    autoheal:
        # container_name: pdp-autoheal
        restart: always
        image: willfarrell/autoheal
        environment:
            - AUTOHEAL_CONTAINER_LABEL=autoheal
            - AUTOHEAL_INTERVAL=5
            - DOCKER_SOCK=/var/run/docker.sock
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        networks:
            - internal

volumes:
    empty_volume: