version: '3.3'
networks:
    support:
        driver: bridge
services:
    tailscale:
        hostname: ${HOSTNAME}_plex_client             # This will become the tailscale device name
        image: tailscale/tailscale:stable
        env_file: 
            - "${DOCKER_ROOT}/config/tailscale-client.env"
        volumes:
            - "${DOCKER_ROOT}/config:/config"
            # - ${DOCKER_ROOT}/tailscale:/var/lib"        # State data will be stored in this directory
            - "/var/lib:/var/lib"        # State data will be stored in this directory
            - "/dev/net/tun:/dev/net/tun"           # Required for tailscale to work
        cap_add:                                    # Required for tailscale to work
          - net_admin
          - sys_module
        logging:
            options:
                max-size: 20m
        # networks:
        #     - support
        network_mode: host
        restart: always
    portainer_portal:
        hostname: portainer_portal
        image: portainer/portainer-ce
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - /var/lib/docker/volumes:/var/lib/docker/volumes
            - portainer_data:/data
        networks:
            - support
        ports:
            - "9443:9443"
        logging:
            options:
                max-size: 20m
        restart: always

volumes:
    portainer_data:
