version: '3.3'
networks:
    support:
        driver: bridge
services:
    rclone_library_sync:
        # container_name: pdp-rclone-library-download
        # # command: 'lsd SECURE_BACKUP:'
        # # library download from master
        # command: 'copy SECURE_BACKUP: /master_data --progress'
        # library upload from master
        command: 'sync /master_data secure_backup: --progress  --filter "- *.db" --filter "- *.db-wal" --filter "- *.db-shm"'
        labels:
            - "autoheal-library=true"
        #command: 'lsd SECURE_BACKUP:'
        environment:
            - TZ=Australia/Melbourne
            - PUID=${USERID}   
            - PGID=${GROUPID}
            - 'RCLONE_CONFIG_SECURE_BACKUP_REMOTE=gdrive_backup_rw:plexdriveplus'
            - RCLONE_CONFIG_SECURE_BACKUP_TYPE=${RCLONE_CONFIG_SECURE_BACKUP_TYPE}
            - RCLONE_CONFIG_SECURE_BACKUP_FILENAME_ENCRYPTION=${RCLONE_CONFIG_SECURE_BACKUP_FILENAME_ENCRYPTION}
            - RCLONE_CONFIG_SECURE_BACKUP_DIRECTORY_NAME_ENCRYPTION=${RCLONE_CONFIG_SECURE_BACKUP_DIRECTORY_NAME_ENCRYPTION}
            - RCLONE_CONFIG_SECURE_BACKUP_PASSWORD=${RCLONE_CONFIG_SECURE_BACKUP_PASSWORD}
            - RCLONE_CONFIG_SECURE_BACKUP_PASSWORD2=${RCLONE_CONFIG_SECURE_BACKUP_PASSWORD2}
        volumes:
            - '${DOCKER_ROOT}/rclone/:/config/rclone:rw'
            - '${DOCKER_ROOT}/plex-scanner/Library/Application Support/Plex Media Server/Plug-in Support/:/master_data/Library/Application Support/Plex Media Server/Plug-in Support/:rw'
            - '${DOCKER_ROOT}/config/:/master_data/config:rw'
            - '${DOCKER_ROOT}/plexdrive/cache/:/master_data/plexdrive/cache:rw'
            - '${DOCKER_ROOT}/plex-scanner/backups/:/master_data/plex-scanner/backups:rw'
        networks:
            - bridge
            - internal
        logging:
            options:
                max-size: 20m
        image: rclone/rclone
    autoheal-library:
        # container_name: pdp-autoheal-library-download
        restart: always
        image: willfarrell/autoheal
        environment:
            - AUTOHEAL_CONTAINER_LABEL=autoheal-library
            - AUTOHEAL_INTERVAL=1440
            - DOCKER_SOCK=/var/run/docker.sock
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        networks:
            - internal
    tailscale:
        hostname: portainer_agent                         # This will become the tailscale device name
        image: tailscale/tailscale
        volumes:
            - ${DOCKER_ROOT}/tailscale:/var/lib"        # State data will be stored in this directory
            - "/dev/net/tun:/dev/net/tun"           # Required for tailscale to work
        cap_add:                                    # Required for tailscale to work
          - net_admin
          - sys_module
        # to authenticate to tailscale run:
        # docker exec plexdriveplus-tailscale-1 tailscale up 
        # or visit url in logs
        networks:
            - support
        restart: always
    myservice-container:
        image: nginx                                # Your image goes here
        network_mode: service:tailscale
    portainer_agent:
        restart: always
        image: portainer/agent
        hostname: portainer_agent
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - /var/lib/docker/volumes:/var/lib/docker/volumes
        networks:
            - internal
    portainer_portal:
        restart: always
        image: portainer/portainer-ce
        command: -H tcp://portainer_agent:9001 --tlsskipverify
        #hostname: portainer_portal
        ports:
            - "9999:9000"
        volumes:
            - portainer_data:/data
        networks:
            - support
            - internal
        network_mode: service:tailscale
    ubuntu:
        depends_on:
            - tailscale
        image: ubuntu
        network_mode: service:tailscale
        command: ["sleep","infinity"]

volumes:
    portainer_data: