version: '3.3'
networks:
    support:
        driver: bridge
services:
    wireguard:
        image: lscr.io/linuxserver/wireguard:latest
        container_name: wireguard
        cap_add:
            - NET_ADMIN
            - SYS_MODULE
        sysctls:
            - net.ipv4.conf.all.src_valid_mark=1
        environment:
            - PGID=${GROUPID}
            - PUID=${USERID}
            - TZ=Australia/Melbourne
        volumes:
            - ${DOCKER_ROOT}/wireguard:/config
        restart: always
        networks:
            - support
    portainer_agent:
        image: portainer/agent:latest
        network_mode: service:wireguard
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - /var/lib/docker/volumes:/var/lib/docker/volumes
        restart: always
        depends_on:
            - wireguard
    portainer_portal_wg:
        restart: always
        image: portainer/portainer-ce
        command: -H tcp://127.0.0.1:9001 --tlsskipverify
        volumes:
            - portainer_wg_data:/data
        depends_on:
            - wireguard
        network_mode: service:wireguard
    ubuntu:
        depends_on:
            - wireguard
        image: ubuntu
        network_mode: service:wireguard
        command: ["sleep","infinity"]
    portainer_portal:
        restart: always
        image: portainer/portainer-ce
        volumes:
            - portainer_data:/data
        networks:
            - support
        ports:
            - "9010:9000"

volumes:
    portainer_data:
    portainer_wg_data: