version: '3.3'
networks:
    support:
        driver: bridge
services:
    tailscale:
        hostname: ${HOSTNAME}_plex_client             # This will become the tailscale device name
        image: tailscale/tailscale:latest
        env_file: 
            - "${DOCKER_ROOT}/config/support.env"
        environment:
            - TS_AUTH_KEY=${TAILSCALE_PLEX_CLIENT_AUTHKEY}
        volumes:
            - ${DOCKER_ROOT}/config:/config"
            - ${DOCKER_ROOT}/tailscale:/var/lib"        # State data will be stored in this directory
            - "/dev/net/tun:/dev/net/tun"           # Required for tailscale to work
        cap_add:                                    # Required for tailscale to work
          - net_admin
          - sys_module
        # networks:
        #     - support
        network_mode: host
        restart: always
    portainer_agent_tailscale:
        hostname: portainer_agent_tailscale
        image: portainer/agent:latest
        networks:
            - support
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - /var/lib/docker/volumes:/var/lib/docker/volumes
        restart: always
        depends_on:
            - tailscale
    portainer_agent:
        hostname: portainer_agent
        image: portainer/agent:latest
        networks:
            - support
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - /var/lib/docker/volumes:/var/lib/docker/volumes
        restart: always
    portainer_portal:
        hostname: portainer_portal
        image: portainer/portainer-ce
        command: -H tcp://portainer_agent:9001 --tlsskipverify
        volumes:
            - portainer_data:/data
        networks:
            - support
        ports:
            - "9443:9443"
            - "9999:9000"
        restart: always

volumes:
    portainer_data:
    portainer_local_data:
