version: '3.3'
networks:
    internal:
services:
    rclone_media_scanner1:
        restart: always
        labels:
            - "autoheal=true"
        environment:
            - TZ=Australia/Melbourne
            - PGID=100
            - PUID=99
            - 'HEALTHCHECK_MOUNTS=/cloud'
            - 'HEALTHCHECK_PATHS=/data /cloud /local'
            # - RCLONE_LOG_FILE=/config/rclone_media_scanner_mount_1.log
            - POOLING_FS=unionfs
            - RCLONE_LOG_LEVEL=INFO
            - 'RCLONE_REMOTE_PATH=secure_media_scanner:'
            - 'RCLONE_MOUNT_USER_OPTS=--read-only --acd-templink-threshold 1g --buffer-size 8M --timeout 5s --contimeout 5s --stats 300s --dir-cache-time 30m --multi-thread-streams=20 --allow-non-empty --allow-other --rc-web-gui --rc-web-gui-update --rc-web-gui-no-open-browser --rc-user ${RCLONE_USER} --rc-pass ${RCLONE_PASSWORD}'
            - RCLONE_CONFIG_GDRIVE_MOLE_TEAM_DRIVE=${RCLONE_CONFIG_GDRIVE_TEAM_DRIVE_1}
            - RCLONE_CONFIG_GDRIVE_WOLF_TEAM_DRIVE=${RCLONE_CONFIG_GDRIVE_TEAM_DRIVE_1}
        volumes:
            - '${DOCKER_ROOT}/rclone/:/config:rw'
            - '${DOCKER_ROOT}/scripts/:/scripts:ro'
            - '${DOCKER_ROOT}/mnt/rclone/secure_media_scanner:/data:rshared'
            - '${DOCKER_ROOT}/mnt/rclone/secure_media_scanner2:/local/:rshared'
        networks:
            - internal
        ports:
            - "25571:5574"
        logging:
            options:
                max-size: 20m
        devices:
            - /dev/fuse
        cap_add:
            - SYS_ADMIN
        security_opt:
            - apparmor:unconfined
        image: wiserain/rclone
        healthcheck:
            test: ["CMD-SHELL", "sh /scripts/healthcheck"]
            interval: 120s
            timeout: 10s
            retries: 1
            start_period: 5s
    rclone_media_scanner2:
        restart: always
        labels:
            - "autoheal=true"
        environment:
            - TZ=Australia/Melbourne
            - PGID=100
            - PUID=99
            - 'HEALTHCHECK_MOUNTS=/cloud'
            - 'HEALTHCHECK_PATHS=/data /cloud /local'
            # - RCLONE_LOG_FILE=/config/rclone_media_scanner_mount_2.log
            - POOLING_FS=unionfs
            - RCLONE_LOG_LEVEL=INFO
            - 'RCLONE_REMOTE_PATH=secure_media_scanner:'
            - 'RCLONE_MOUNT_USER_OPTS=--read-only --acd-templink-threshold 1g --buffer-size 8M --timeout 5s --contimeout 5s --stats 300s --dir-cache-time 30m --multi-thread-streams=20 --allow-non-empty --allow-other --rc-web-gui --rc-web-gui-update --rc-web-gui-no-open-browser --rc-user ${RCLONE_USER} --rc-pass ${RCLONE_PASSWORD}'
            - RCLONE_CONFIG_GDRIVE_MOLE_TEAM_DRIVE=${RCLONE_CONFIG_GDRIVE_TEAM_DRIVE_2}
            - RCLONE_CONFIG_GDRIVE_WOLF_TEAM_DRIVE=${RCLONE_CONFIG_GDRIVE_TEAM_DRIVE_2}
        volumes:
            - '${DOCKER_ROOT}/rclone/:/config:rw'
            - '${DOCKER_ROOT}/scripts/:/scripts:ro'
            - '${DOCKER_ROOT}/mnt/rclone/secure_media_scanner2:/data:rshared'
            - '${DOCKER_ROOT}/mnt/rclone/secure_media_scanner3:/local/:rshared'
        networks:
            - internal
        ports:
            - "25572:5574"
        logging:
            options:
                max-size: 20m
        devices:
            - /dev/fuse
        cap_add:
            - SYS_ADMIN
        security_opt:
            - apparmor:unconfined
        image: wiserain/rclone
        healthcheck:
            test: ["CMD-SHELL", "sh /scripts/healthcheck"]
            interval: 120s
            timeout: 10s
            retries: 1
            start_period: 5s
    rclone_media_scanner3:
        restart: always
        labels:
            - "autoheal=true"
        environment:
            - TZ=Australia/Melbourne
            - PGID=100
            - PUID=99
            - 'HEALTHCHECK_MOUNTS=/cloud'
            - 'HEALTHCHECK_PATHS=/data /cloud'
            # - RCLONE_LOG_FILE=/config/rclone_media_scanner_mount_3.log
            - POOLING_FS=unionfs
            - RCLONE_LOG_LEVEL=INFO
            - 'RCLONE_REMOTE_PATH=secure_media_scanner:'
            - 'RCLONE_MOUNT_USER_OPTS=--read-only --acd-templink-threshold 1g --buffer-size 8M --timeout 5s --contimeout 5s --stats 300s --dir-cache-time 30m --multi-thread-streams=20 --allow-non-empty --allow-other --rc-web-gui --rc-web-gui-update --rc-web-gui-no-open-browser --rc-user ${RCLONE_USER} --rc-pass ${RCLONE_PASSWORD}'
            - RCLONE_CONFIG_GDRIVE_MOLE_TEAM_DRIVE=${RCLONE_CONFIG_GDRIVE_TEAM_DRIVE_3}
            - RCLONE_CONFIG_GDRIVE_WOLF_TEAM_DRIVE=${RCLONE_CONFIG_GDRIVE_TEAM_DRIVE_3}
        volumes:
            - '${DOCKER_ROOT}/rclone/:/config:rw'
            - '${DOCKER_ROOT}/scripts/:/scripts:ro'
            - '${DOCKER_ROOT}/mnt/rclone/secure_media_scanner3:/data:rshared'
            - 'rclone_empty_volume:/local/:rshared'
        networks:
            - internal
        ports:
            - "25573:5574"
        logging:
            options:
                max-size: 20m
        devices:
            - /dev/fuse
        cap_add:
            - SYS_ADMIN
        security_opt:
            - apparmor:unconfined
        image: wiserain/rclone
        healthcheck:
            test: ["CMD-SHELL", "sh /scripts/healthcheck"]
            interval: 120s
            timeout: 10s
            retries: 1
            start_period: 5s
    plex_scanner:
        # container_name: pdp-plex-scanner
        networks:
            - internal
        restart: always
        labels:
            - "autoheal=true"
        environment:
            - TZ=Australia/Melbourne
            - PLEX_CLAIM=${PLEX_CLAIM}
            - PLEX_UID=99
            - PLEX_GID=100
            - VERSION=latest
            - 'NVIDIA_VISIBLE_DEVICES='
            - PUID=99
            - PGID=100
            - 'RCLONE_MEDIA_PATH=/mnt/rclone/secure_media_scanner/Media'
            - 'PLEXDRIVE_MEDIA_PATH=/mnt/rclone/secure_media_plexdrive/Media'
            - 'PLEXDRIVE_MEDIA_FOLDERS='
            - 'HEALTHCHECK_MOUNTS=/mnt/rclone/secure_media_scanner'
            - 'HEALTHCHECK_PATHS=/plex/media/Media/tv-4k'
        volumes:
            - '${DOCKER_ROOT}/mnt/rclone/secure_media_scanner/:/mnt/rclone/secure_media_scanner:rshared'
            - '${DOCKER_ROOT}/plex-scanner/:/config:rw'
            - '${DOCKER_ROOT}/scripts/:/scripts:ro'
        ports:
            - "34400:32400"
        image: linuxserver/plex
        healthcheck:
            test: ["CMD-SHELL", "bash /scripts/plexhealthcheck"]
            interval: 300s
            timeout: 60s
            retries: 3
            start_period: 30s
        # depends_on:
            # rclone_media_scanner:
                # condition: service_healthy