version: '3.3'
services:
    # rclone_library_sync:
    #     # container_name: pdp-rclone-library-download
    #     # # command: 'lsd SECURE_BACKUP:'
    #     # library download from master, exclude current db files s they are usually corrupt
    #     # command: 'copy SECURE_BACKUP:Library /config/Library --progress --filter "- *.db" --filter "- *.db-wal" --filter "- *.db-shm"'
    #     command: 'sync SECURE_BACKUP: /config --progress --filter "+ /Library/**" --filter "- /config/.env" --filter "+ /config/**" --filter "- *"'
    #     # # library upload from master
    #     # command: 'sync /config SECURE_BACKUP: --progress'
    #     labels:
    #         - "autoheal-library=true"
    #     #command: 'lsd SECURE_BACKUP:'
    #     environment:
    #         - TZ=Australia/Melbourne
    #         - PUID=${USERID}
    #         - PGID=${GROUPID}
    #     env_file: 
    #         - "${DOCKER_ROOT}/config/rclone.env"
    #     volumes:
    #         - '${DOCKER_ROOT}/plex-scanner/Library/Application Support/Plex Media Server/Plug-in Support/:/config/Library/Application Support/Plex Media Server/Plug-in Support/:rw'
    #     networks:
    #         - bridge
    #         - internal
    #     user: "${USERID}:${GROUPID}"
    #     logging:
    #         options:
    #             max-size: 20m
    #     image: rclone/rclone
    rclone_library_sync:
        #command: 'sync SECURE_BACKUP: /config --progress --filter "+ /Library/**" --filter "- /config/.env" --filter "+ /config/**" --filter "- *"'
        command: 'sync SECURE_BACKUP: /master_data --progress --filter "+ /plex_library_backup/**" --filter "- *"'
        labels:
            - "autoheal-library=true"
        environment:
            - TZ=Australia/Melbourne
            - PUID=${USERID}
            - PGID=${GROUPID}
        env_file: 
            - "${DOCKER_ROOT}/config/rclone.env"
        volumes:
            - '${LARGE_DISK_ROOT}/plex_master_backup:/master_data/plex_library_backup:rw'
                # mount path containing done file --filter-from /library_path_local/library_images_loaded.dat
            - '${DOCKER_ROOT}/plex-streamer/Library/Application Support/Plex Media Server:/library_path_local:rw'
        networks:
            - bridge
            - internal
        user: "${USERID}:${GROUPID}"
        logging:
            options:
                max-size: 20m
        image: rclone/rclone
    incremental_library_images_restore:
        labels:
            - "autoheal-library=true"
        environment:
            - TZ=Australia/Melbourne
            - PUID=${USERID}
            - PGID=${GROUPID}
            - EXTRACTED_FILES_PATH=/library_path_local
            - TMP_PATH=/library_path_local
            - CONFIG_PATH=/config
            - RCLONE_REMOTE=SECURE_BACKUP
            - RCLONE_PATH=plex_library_backup/meta
            - MODE=RESTORE
            - MIN_DISK_SPACE=52428800
            - TAR_FILENAME_START=library_images
        env_file:
            - "${DOCKER_ROOT}/config/rclone.env"
        volumes:
            - '${DOCKER_ROOT}/plex-streamer/Library/Application Support/Plex Media Server:/library_path_local:rw'
            - '${DOCKER_ROOT}/incremental_library_images_restore:/config:rw'
        networks:
            - bridge
            - internal
        # user: "${USERID}:${GROUPID}"
        logging:
            options:
                max-size: 20m
        image: slink42/incremental-folder-sync:latest
    autoheal-library:
        # container_name: pdp-autoheal-library-download
        restart: always
        image: willfarrell/autoheal
        environment:
            - AUTOHEAL_CONTAINER_LABEL=autoheal-library
            - AUTOHEAL_INTERVAL=1440
            - DOCKER_SOCK=/var/run/docker.sock
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        networks:
            - internal
