version: '3.3'
networks:
    internal:
        internal: true
    bridge:
        driver: bridge
    hostnet:
        external: true
        name: host
services:
    rclone_media1:
        restart: always
        labels:
            - "autoheal=true"
        environment:
            - TZ=Australia/Melbourne
            - PGID=${GROUPID}
            - PUID=${USERID}
            #- RCLONE_LOG_FILE=/config/rclone_media_mount_1.log
            - RCLONE_LOG_LEVEL=INFO
            - 'RCLONE_REMOTE_PATH=pd_secure_media_union:'
            - 'RCLONE_MOUNT_USER_OPTS=--read-only --use-json-log --acd-templink-threshold 1g --buffer-size 8M --timeout 5s --contimeout 5s --stats 300s --dir-cache-time 30m --multi-thread-streams=20 --allow-non-empty --allow-other --rc-web-gui --rc-web-gui-no-open-browser --rc-user ${RCLONE_USER} --rc-pass ${RCLONE_PASSWORD}'
            - RCLONE_CONFIG_GDRIVE_MOLE_TEAM_DRIVE=${RCLONE_CONFIG_GDRIVE_TEAM_DRIVE_1}
            - RCLONE_CONFIG_GDRIVE_WOLF_TEAM_DRIVE=${RCLONE_CONFIG_GDRIVE_TEAM_DRIVE_1}
            - MERGED_DEST=/mnt/rclone/secure_media
        env_file: 
            - "${DOCKER_ROOT}/config/rclone.env"
        volumes:
            - '${DOCKER_ROOT}/rclone/:/config:rw'
            - '${DOCKER_ROOT}/mnt/rclone:/mnt/rclone:shared'
        networks:
            - bridge
            - internal
        ports:
            - "15571:5574"
        logging:
            options:
                max-size: 20m
        devices:
            - /dev/fuse
        cap_add:
            - SYS_ADMIN
        security_opt:
            - apparmor:unconfined
        image: slink42/rclone
    plexdrive1:
        restart: always
        labels:
            - "autoheal=true"
        environment:
            - TZ=Australia/Melbourne
            - PUID=${USERID}
            - PGID=${GROUPID}
            - 'PLEXDRIVE_OPTS=-v 2 --max-chunks=10 --chunk-size=20M --chunk-check-threads=20 --chunk-load-threads=4 --chunk-load-ahead=5 --drive-id=${RCLONE_CONFIG_GDRIVE_TEAM_DRIVE_1} -o allow_other,read_only,nonempty,auto_unmount'
        env_file: 
            - "${DOCKER_ROOT}/config/rclone.env"
        volumes:
            - '${DOCKER_ROOT}/plexdrive/config:/config:rw'
            - '${DOCKER_ROOT}/mnt/plexdrive/secure_media:/data:shared'
        networks:
            - bridge
            - internal
        logging:
            options:
                max-size: 20m
        devices:
            - /dev/fuse
        cap_add:
            - SYS_ADMIN
        security_opt:
            - apparmor:unconfined
        image: 'wiserain/plexdrive'
    rclone_plexdrive1:
        restart: always
        labels:
            - "autoheal=true"
        environment:
            - TZ=Australia/Melbourne
            - PGID=${GROUPID}
            - PUID=${USERID}
            #- RCLONE_LOG_FILE=/config/rclone_plexdrive1_mount.log
            - RCLONE_LOG_LEVEL=INFO
            - 'RCLONE_REMOTE_PATH=plexdrive_securemedia_crypt:'
            - 'RCLONE_MOUNT_USER_OPTS=--include=mountcheck --include=Media/tv-4k/** --include=Media/movies-4k/** --read-only --use-json-log --dir-cache-time 30m --multi-thread-streams=20 --allow-non-empty --allow-other --rc-web-gui --rc-web-gui-no-open-browser --rc-user ${RCLONE_USER} --rc-pass ${RCLONE_PASSWORD}'
            - MERGED_DEST=/mnt/rclone/plexdrive_secure_media
        env_file: 
            - "${DOCKER_ROOT}/config/rclone.env"
        volumes:
            - '${DOCKER_ROOT}/rclone/:/config:rw'
            - '${DOCKER_ROOT}/mnt/plexdrive:/mnt/plexdrive:slave'
            - '${DOCKER_ROOT}/mnt/rclone:/mnt/rclone:shared'
        networks:
            - bridge
            - internal
        ports:
            - "15574:5574"
        logging:
            options:
                max-size: 20m
        devices:
            - /dev/fuse
        cap_add:
            - SYS_ADMIN
        security_opt:
            - apparmor:unconfined
        image: slink42/rclone
        depends_on:
            plexdrive1:
                condition: service_healthy
    plex_streamer:
        network_mode: host
        # networks:
        #     - bridge
        #     - internal
        restart: always
        labels:
            - "autoheal=true"
        environment:
            - TZ=Australia/Melbourne
            - HOST_OS=Unraid
            - PLEX_CLAIM=${PLEX_CLAIM}
            - PLEX_UID=${USERID}
            - PLEX_GID=${GROUPID}
            - VERSION=latest
            - 'NVIDIA_VISIBLE_DEVICES='
            - TCP_PORT_32400=32400
            - TCP_PORT_3005=3005
            - TCP_PORT_8324=8324
            - TCP_PORT_32469=32469
            - UDP_PORT_1900=1900
            - UDP_PORT_32410=32410
            - UDP_PORT_32412=32412
            - UDP_PORT_32413=32413
            - UDP_PORT_32414=32414
            - PUID=${USERID}
            - PGID=${GROUPID}
            - LOAD_LIBRARY_DB_TO_MEMORY=${LOAD_LIBRARY_DB_TO_MEMORY}
            - 'SCANNER_LIBRARY_PATH=/mnt/plex-scanner/Library/Application Support/Plex Media Server'
            - 'HEALTHCHECK_MOUNTS=/plex/media'
            - 'HEALTHCHECK_PATHS=/plex/media/mountcheck'
            - 'LIB_BACKUP_PATH_MASTER=/backups/databases'
            - 'LIB_BACKUP_PATH_LOCAL=/config/Library/Application Support/Plex Media Server/Plug-in Support/Databases'
            - 'LIB_RELOAD_CRON=35 5 * * *'
            - 'LIB_META_BACKUP_PATH_MASTER=/backups/meta'
        volumes:
            - '${DOCKER_ROOT}/plex-streamer/transcode:/transcode:rw'
            - '${DOCKER_ROOT}/mnt/rclone/secure_media:/plex:slave'
            - '${DOCKER_ROOT}/plex-streamer/:/config:rw'
            # - '${DOCKER_ROOT}/plex-streamer/custom-scripts:/custom-cont-init.d:ro'
            # - '${DOCKER_ROOT}/plex-streamer/custom-services:/custom-services.d:ro'
            - '${LARGE_DISK_ROOT}/plex_master_backup:/backups:rw'
            - '${LARGE_DISK_ROOT}/tmp:/tmp:rw'
        tmpfs:
            - /ram_disk
        ports:
            - "32400:32400"
        image: slink42/plex
        # depends_on:
        #     streamer_mergerfs:
        #         condition: service_healthy
    autoheal:
        image: willfarrell/autoheal
        environment:
            - AUTOHEAL_CONTAINER_LABEL=autoheal
            - AUTOHEAL_INTERVAL=5
            - DOCKER_SOCK=/var/run/docker.sock
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        networks:
            - internal
        restart: always
    watchtower:
        image: containrrr/watchtower
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        command: --interval 30 --include-stopped
        restart: always

volumes:
    empty_volume: